#!/usr/bin/env python3
"""额外名言数据 - 600+ 条新增名言"""

EXTRA_QUOTES = [
    # ===== 爱情 =====
    {"text": "你若不离不弃，我必生死相依。", "author": "佚名", "cats": ["aiqing", "jianchi"]},
    {"text": "执子之手，与子偕老。", "author": "诗经", "cats": ["aiqing", "gushi"]},
    {"text": "关关雎鸠，在河之洲。窈窕淑女，君子好逑。", "author": "诗经", "cats": ["aiqing", "gushi"]},
    {"text": "蒹葭苍苍，白露为霜。所谓伊人，在水一方。", "author": "诗经", "cats": ["aiqing", "gushi", "siyuan"]},
    {"text": "山有木兮木有枝，心悦君兮君不知。", "author": "越人歌", "cats": ["aiqing", "gushi", "siyuan"]},
    {"text": "此情可待成追忆，只是当时已惘然。", "author": "李商隐", "cats": ["aiqing", "gushi", "yiHan"]},
    {"text": "十年生死两茫茫，不思量，自难忘。", "author": "苏轼", "cats": ["aiqing", "gushi", "siNian"]},
    {"text": "花自飘零水自流，一种相思，两处闲愁。", "author": "李清照", "cats": ["aiqing", "gushi", "siyuan"]},
    {"text": "此情无计可消除，才下眉头，却上心头。", "author": "李清照", "cats": ["aiqing", "gushi", "siNian"]},
    {"text": "莫道不销魂，帘卷西风，人比黄花瘦。", "author": "李清照", "cats": ["aiqing", "gushi", "siNian"]},
    {"text": "寻寻觅觅，冷冷清清，凄凄惨惨戚戚。", "author": "李清照", "cats": ["aiqing", "gushi", "gudu"]},
    {"text": "只愿君心似我心，定不负相思意。", "author": "李之仪", "cats": ["aiqing", "gushi", "siNian"]},
    {"text": "问君能有几多愁？恰似一江春水向东流。", "author": "李煜", "cats": ["aiqing", "gushi", "tongku"]},
    {"text": "人生自是有情痴，此恨不关风与月。", "author": "欧阳修", "cats": ["aiqing", "gushi"]},
    {"text": "身无彩凤双飞翼，心有灵犀一点通。", "author": "李商隐", "cats": ["aiqing", "gushi"]},
    {"text": "春心莫共花争发，一寸相思一寸灰。", "author": "李商隐", "cats": ["aiqing", "gushi", "tongku"]},
    {"text": "相见时难别亦难，东风无力百花残。", "author": "李商隐", "cats": ["aiqing", "liuxue", "gushi"]},
    {"text": "刘郎已恨蓬山远，更隔蓬山一万重。", "author": "李商隐", "cats": ["aiqing", "gushi", "siNian"]},
    {"text": "曾经沧海难为水，除却巫山不是云。", "author": "元稹", "cats": ["aiqing", "gushi", "siNian"]},
    {"text": "不是花中偏爱菊，此花开尽更无花。", "author": "元稹", "cats": ["aiqing", "gushi", "zhongQing"]},
    {"text": "与君初相识，犹如故人归。", "author": "佚名", "cats": ["aiqing", "youqing"]},
    {"text": "平生不会相思，才会相思，便害相思。", "author": "徐再思", "cats": ["aiqing", "gushi", "siNian"]},
    {"text": "碧云天，黄叶地，秋色连波，波上寒烟翠。", "author": "范仲淹", "cats": ["aiqing", "gushi", "qiuYi"]},
    {"text": "酒入愁肠，化作相思泪。", "author": "范仲淹", "cats": ["aiqing", "gushi", "siNian"]},
    {"text": "衣带渐宽终不悔，为伊消得人憔悴。", "author": "柳永", "cats": ["aiqing", "jianchi", "gushi"]},
    {"text": "多情自古伤离别，更那堪，冷落清秋节。", "author": "柳永", "cats": ["aiqing", "liuxue", "gushi"]},
    {"text": "便纵有千种风情，更与何人说。", "author": "柳永", "cats": ["aiqing", "gushi", "gudu"]},
    {"text": "两情若是久长时，又岂在朝朝暮暮。", "author": "秦观", "cats": ["aiqing", "gushi", "mingren"]},
    {"text": "自在飞花轻似梦，无边丝雨细如愁。", "author": "秦观", "cats": ["aiqing", "gushi", "youShang"]},
    {"text": "柔情似水，佳期如梦，忍顾鹊桥归路。", "author": "秦观", "cats": ["aiqing", "gushi"]},

    # ===== 励志 =====
    {"text": "大鹏一日同风起，扶摇直上九万里。", "author": "李白", "cats": ["lizhi", "gushi", "mengxiang"]},
    {"text": "俱怀逸兴壮思飞，欲上青天揽明月。", "author": "李白", "cats": ["lizhi", "gushi", "mengxiang"]},
    {"text": "仰天大笑出门去，我辈岂是蓬蒿人。", "author": "李白", "cats": ["lizhi", "gushi", "zixin"]},
    {"text": "安能摧眉折腰事权贵，使我不得开心颜！", "author": "李白", "cats": ["lizhi", "gushi", "zunYan"]},
    {"text": "长风破浪会有时，直挂云帆济沧海。", "author": "李白", "cats": ["lizhi", "mengxiang", "gushi"]},
    {"text": "天生我材必有用，千金散尽还复来。", "author": "李白", "cats": ["lizhi", "zixin", "gushi"]},
    {"text": "会当凌绝顶，一览众山小。", "author": "杜甫", "cats": ["lizhi", "gushi", "gaodu"]},
    {"text": "读书破万卷，下笔如有神。", "author": "杜甫", "cats": ["lizhi", "xuexi", "gushi"]},
    {"text": "出师未捷身先死，长使英雄泪满襟。", "author": "杜甫", "cats": ["lizhi", "gushi", "beiZhuang"]},
    {"text": "安得广厦千万间，大庇天下寒士俱欢颜。", "author": "杜甫", "cats": ["lizhi", "gushi", "aiGuo"]},
    {"text": "会挽雕弓如满月，西北望，射天狼。", "author": "苏轼", "cats": ["lizhi", "gushi", "haoQing"]},
    {"text": "古之立大事者，不惟有超世之才，亦必有坚忍不拔之志。", "author": "苏轼", "cats": ["lizhi", "gushi", "jianchi"]},
    {"text": "人生自古谁无死，留取丹心照汗青。", "author": "文天祥", "cats": ["lizhi", "aiGuo", "gushi"]},
    {"text": "粉骨碎身浑不怕，要留清白在人间。", "author": "于谦", "cats": ["lizhi", "daode", "gushi"]},
    {"text": "咬定青山不放松，立根原在破岩中。", "author": "郑板桥", "cats": ["lizhi", "jianchi", "gushi"]},
    {"text": "千磨万击还坚劲，任尔东西南北风。", "author": "郑板桥", "cats": ["lizhi", "jianchi", "gushi"]},
    {"text": "海纳百川，有容乃大；壁立千仞，无欲则刚。", "author": "林则徐", "cats": ["lizhi", "daode", "gushi"]},
    {"text": "苟利国家生死以，岂因祸福避趋之。", "author": "林则徐", "cats": ["lizhi", "aiGuo", "gushi"]},
    {"text": "世上无难事，只要肯登攀。", "author": "毛泽东", "cats": ["lizhi", "jianchi", "mingren"]},
    {"text": "俱往矣，数风流人物，还看今朝。", "author": "毛泽东", "cats": ["lizhi", "haoQing", "mingren"]},
    {"text": "雄关漫道真如铁，而今迈步从头越。", "author": "毛泽东", "cats": ["lizhi", "jianchi", "mingren"]},
    {"text": "不到长城非好汉，屈指行程二万。", "author": "毛泽东", "cats": ["lizhi", "jianchi", "mingren"]},
    {"text": "为中华之崛起而读书。", "author": "周恩来", "cats": ["lizhi", "xuexi", "mingren"]},
    {"text": "吾志所向，一往无前，愈挫愈奋，再接再厉。", "author": "孙中山", "cats": ["lizhi", "jianchi", "mingren"]},
    {"text": "革命尚未成功，同志仍需努力。", "author": "孙中山", "cats": ["lizhi", "jianchi", "mingren"]},
    {"text": "人不可有傲气，但不可无傲骨。", "author": "徐悲鸿", "cats": ["lizhi", "zixin", "mingren"]},
    {"text": "路漫漫其修远兮，吾将上下而求索。", "author": "屈原", "cats": ["lizhi", "jianchi", "gushi"]},
    {"text": "亦余心之所善兮，虽九死其犹未悔。", "author": "屈原", "cats": ["lizhi", "jianchi", "gushi"]},
    {"text": "老骥伏枥，志在千里；烈士暮年，壮心不已。", "author": "曹操", "cats": ["lizhi", "lxiang", "gushi"]},
    {"text": "周公吐哺，天下归心。", "author": "曹操", "cats": ["lizhi", "yeXin", "gushi"]},
    {"text": "穷且益坚，不坠青云之志。", "author": "王勃", "cats": ["lizhi", "lxiang", "gushi"]},
    {"text": "宁为百夫长，胜作一书生。", "author": "杨炯", "cats": ["lizhi", "baoGuo", "gushi"]},
    {"text": "黄沙百战穿金甲，不破楼兰终不还。", "author": "王昌龄", "cats": ["lizhi", "jianchi", "gushi"]},
    {"text": "但使龙城飞将在，不教胡马度阴山。", "author": "王昌龄", "cats": ["lizhi", "aiGuo", "gushi"]},
    {"text": "莫愁前路无知己，天下谁人不识君。", "author": "高适", "cats": ["lizhi", "youqing", "gushi"]},

    # ===== 人生 =====
    {"text": "对酒当歌，人生几何？", "author": "曹操", "cats": ["rensheng", "gushi", "kuaile"]},
    {"text": "譬如朝露，去日苦多。", "author": "曹操", "cats": ["rensheng", "gushi", "shijian"]},
    {"text": "人生如梦，一尊还酹江月。", "author": "苏轼", "cats": ["rensheng", "gushi", "gankai"]},
    {"text": "人有悲欢离合，月有阴晴圆缺，此事古难全。", "author": "苏轼", "cats": ["rensheng", "gushi", "tongku"]},
    {"text": "竹杖芒鞋轻胜马，谁怕？一蓑烟雨任平生。", "author": "苏轼", "cats": ["rensheng", "gushi", "saTuo"]},
    {"text": "回首向来萧瑟处，归去，也无风雨也无晴。", "author": "苏轼", "cats": ["rensheng", "gushi", "kuaile"]},
    {"text": "人生到处知何似，应似飞鸿踏雪泥。", "author": "苏轼", "cats": ["rensheng", "gushi", "gankai"]},
    {"text": "不识庐山真面目，只缘身在此山中。", "author": "苏轼", "cats": ["rensheng", "zhihui", "gushi"]},
    {"text": "人生得意须尽欢，莫使金樽空对月。", "author": "李白", "cats": ["rensheng", "kuaile", "gushi"]},
    {"text": "人生在世不称意，明朝散发弄扁舟。", "author": "李白", "cats": ["rensheng", "gushi", "saTuo"]},
    {"text": "举杯邀明月，对影成三人。", "author": "李白", "cats": ["rensheng", "gushi", "gudu"]},
    {"text": "抽刀断水水更流，举杯消愁愁更愁。", "author": "李白", "cats": ["rensheng", "gushi", "tongku"]},
    {"text": "天生我材必有用，千金散尽还复来。", "author": "李白", "cats": ["rensheng", "lizhi", "gushi"]},
    {"text": "尔曹身与名俱灭，不废江河万古流。", "author": "杜甫", "cats": ["rensheng", "gushi", "shiJian"]},
    {"text": "文章千古事，得失寸心知。", "author": "杜甫", "cats": ["rensheng", "gushi", "wenXue"]},
    {"text": "出师未捷身先死，长使英雄泪满襟。", "author": "杜甫", "cats": ["rensheng", "gushi", "beiZhuang"]},
    {"text": "千载琵琶作胡语，分明怨恨曲中论。", "author": "杜甫", "cats": ["rensheng", "gushi", "beiAi"]},
    {"text": "同是天涯沦落人，相逢何必曾相识。", "author": "白居易", "cats": ["rensheng", "gushi", "youqing"]},
    {"text": "天长地久有时尽，此恨绵绵无绝期。", "author": "白居易", "cats": ["rensheng", "gushi", "yiHan"]},
    {"text": "人生代代无穷已，江月年年只相似。", "author": "张若虚", "cats": ["rensheng", "gushi", "shiJian"]},
    {"text": "不知江月待何人，但见长江送流水。", "author": "张若虚", "cats": ["rensheng", "gushi", "shiJian"]},
    {"text": "江畔何人初见月？江月何年初照人？", "author": "张若虚", "cats": ["rensheng", "gushi", "zheLi"]},
    {"text": "前不见古人，后不见来者。", "author": "陈子昂", "cats": ["rensheng", "gushi", "gudu"]},
    {"text": "念天地之悠悠，独怆然而涕下。", "author": "陈子昂", "cats": ["rensheng", "gushi", "beiZhuang"]},
    {"text": "夕阳无限好，只是近黄昏。", "author": "李商隐", "cats": ["rensheng", "gushi", "xiShi"]},
    {"text": "此情可待成追忆，只是当时已惘然。", "author": "李商隐", "cats": ["rensheng", "gushi", "yiHan"]},
    {"text": "世界上只有一种真正的英雄主义，那就是在认清生活的真相后依然热爱生活。", "author": "罗曼·罗兰", "cats": ["rensheng", "yongqi", "kuaile"]},
    {"text": "人生就像骑自行车，想保持平衡就得往前走。", "author": "爱因斯坦", "cats": ["rensheng", "chengzhang", "mingren"]},
    {"text": "人生的价值，并不是用时间，而是用深度去衡量的。", "author": "列夫·托尔斯泰", "cats": ["rensheng", "jiazhi", "mingren"]},
    {"text": "人生不是一支短短的蜡烛，而是一支由我们暂时拿着的火炬。", "author": "萧伯纳", "cats": ["rensheng", "jiazhi"]},
    {"text": "生活不是等待风暴过去，而是学会在雨中跳舞。", "author": "维维安·格林", "cats": ["rensheng", "yongqi", "kuaile"]},
    {"text": "人生最大的荣耀不在于从不跌倒，而在于每次跌倒后都爬起来。", "author": "纳尔逊·曼德拉", "cats": ["rensheng", "shibai", "jianchi"]},
    {"text": "人的一生可能燃烧也可能腐朽，我不能腐朽，我愿意燃烧起来！", "author": "奥斯特洛夫斯基", "cats": ["rensheng", "jiazhi", "lizhi"]},
    {"text": "人最宝贵的是生命，生命对人来说只有一次。", "author": "奥斯特洛夫斯基", "cats": ["rensheng", "zhenXi", "shengMing"]},
    {"text": "当他回首往事时，不因虚度年华而悔恨，也不因碌碌无为而羞耻。", "author": "奥斯特洛夫斯基", "cats": ["rensheng", "fenDou", "lizhi"]},

    # ===== 学习/读书 =====
    {"text": "书到用时方恨少，事非经过不知难。", "author": "古训", "cats": ["xuexi", "dushu", "gushi"]},
    {"text": "腹有诗书气自华。", "author": "苏轼", "cats": ["xuexi", "dushu", "gushi"]},
    {"text": "发奋识遍天下字，立志读尽人间书。", "author": "苏轼", "cats": ["xuexi", "dushu", "lizhi"]},
    {"text": "旧书不厌百回读，熟读深思子自知。", "author": "苏轼", "cats": ["xuexi", "dushu", "gushi"]},
    {"text": "读书有三到，谓心到、眼到、口到。", "author": "朱熹", "cats": ["xuexi", "dushu", "gushi"]},
    {"text": "问渠那得清如许，为有源头活水来。", "author": "朱熹", "cats": ["xuexi", "gushi", "zhihui"]},
    {"text": "少年易老学难成，一寸光阴不可轻。", "author": "朱熹", "cats": ["xuexi", "shijian", "gushi"]},
    {"text": "立身以立学为先，立学以读书为本。", "author": "欧阳修", "cats": ["xuexi", "dushu", "gushi"]},
    {"text": "学而不厌，诲人不倦。", "author": "孔子", "cats": ["xuexi", "gushi", "jiaoYu"]},
    {"text": "温故而知新，可以为师矣。", "author": "孔子", "cats": ["xuexi", "gushi"]},
    {"text": "知之者不如好之者，好之者不如乐之者。", "author": "孔子", "cats": ["xuexi", "kuaile", "gushi"]},
    {"text": "三人行，必有我师焉。", "author": "孔子", "cats": ["xuexi", "qianxu", "gushi"]},
    {"text": "学而不思则罔，思而不学则殆。", "author": "孔子", "cats": ["xuexi", "zhihui", "gushi"]},
    {"text": "知之为知之，不知为不知，是知也。", "author": "孔子", "cats": ["xuexi", "zhihui", "gushi"]},
    {"text": "敏而好学，不耻下问。", "author": "孔子", "cats": ["xuexi", "qianxu", "gushi"]},
    {"text": "学而时习之，不亦说乎？", "author": "孔子", "cats": ["xuexi", "gushi", "mingren"]},
    {"text": "吾生也有涯，而知也无涯。", "author": "庄子", "cats": ["xuexi", "gushi", "wuQiong"]},
    {"text": "吾十有五而志于学，三十而立，四十而不惑。", "author": "孔子", "cats": ["xuexi", "rensheng", "gushi"]},
    {"text": "玉不琢，不成器；人不学，不知道。", "author": "礼记", "cats": ["xuexi", "lizhi", "gushi"]},
    {"text": "学然后知不足，教然后知困。", "author": "礼记", "cats": ["xuexi", "gushi"]},
    {"text": "博学之，审问之，慎思之，明辨之，笃行之。", "author": "礼记", "cats": ["xuexi", "gushi", "fangFa"]},
    {"text": "书山有路勤为径，学海无涯苦作舟。", "author": "韩愈", "cats": ["xuexi", "lizhi", "gushi"]},
    {"text": "业精于勤，荒于嬉；行成于思，毁于随。", "author": "韩愈", "cats": ["xuexi", "lizhi", "gushi"]},
    {"text": "黑发不知勤学早，白首方悔读书迟。", "author": "颜真卿", "cats": ["xuexi", "shijian", "gushi"]},
    {"text": "读书破万卷，下笔如有神。", "author": "杜甫", "cats": ["xuexi", "gushi"]},
    {"text": "纸上得来终觉浅，绝知此事要躬行。", "author": "陆游", "cats": ["xuexi", "shijian", "gushi"]},
    {"text": "古人学问无遗力，少壮工夫老始成。", "author": "陆游", "cats": ["xuexi", "jianchi", "gushi"]},
    {"text": "王师北定中原日，家祭无忘告乃翁。", "author": "陆游", "cats": ["xuexi", "aiGuo", "gushi"]},
    {"text": "知识就是力量。", "author": "培根", "cats": ["xuexi", "zhihui", "mingren"]},
    {"text": "读书是在别人思想的帮助下，建立起自己的思想。", "author": "鲁巴金", "cats": ["xuexi", "zhihui"]},
    {"text": "我学习了一生，现在我还在学习。", "author": "别林斯基", "cats": ["xuexi", "chengzhang"]},
    {"text": "活到老，学到老。", "author": "古训", "cats": ["xuexi", "chengzhang"]},
    {"text": "天才是百分之一的灵感加百分之九十九的汗水。", "author": "爱迪生", "cats": ["xuexi", "gongzuo", "mingren"]},
    {"text": "学到很多东西的诀窍，就是一下子不要学很多。", "author": "洛克", "cats": ["xuexi", "fangfa"]},

    # ===== 古诗名句 =====
    {"text": "大漠孤烟直，长河落日圆。", "author": "王维", "cats": ["gushi", "zhuangGuan"]},
    {"text": "明月松间照，清泉石上流。", "author": "王维", "cats": ["gushi", "meiLi", "jingSe"]},
    {"text": "空山新雨后，天气晚来秋。", "author": "王维", "cats": ["gushi", "meiLi", "qiuTian"]},
    {"text": "行到水穷处，坐看云起时。", "author": "王维", "cats": ["gushi", "renSheng", "zheLi"]},
    {"text": "劝君更尽一杯酒，西出阳关无故人。", "author": "王维", "cats": ["gushi", "youqing", "liuxue"]},
    {"text": "独在异乡为异客，每逢佳节倍思亲。", "author": "王维", "cats": ["gushi", "siyuan", "xiangchou"]},
    {"text": "红豆生南国，春来发几枝。", "author": "王维", "cats": ["gushi", "aiqing", "siNian"]},
    {"text": "春眠不觉晓，处处闻啼鸟。", "author": "孟浩然", "cats": ["gushi", "chunTian", "meiLi"]},
    {"text": "夜来风雨声，花落知多少。", "author": "孟浩然", "cats": ["gushi", "youShang", "chunTian"]},
    {"text": "气蒸云梦泽，波撼岳阳城。", "author": "孟浩然", "cats": ["gushi", "zhuangGuan"]},
    {"text": "野旷天低树，江清月近人。", "author": "孟浩然", "cats": ["gushi", "meiLi", "jingSe"]},
    {"text": "欲穷千里目，更上一层楼。", "author": "王之涣", "cats": ["gushi", "lizhi", "jinBu"]},
    {"text": "白日依山尽，黄河入海流。", "author": "王之涣", "cats": ["gushi", "zhuangGuan"]},
    {"text": "羌笛何须怨杨柳，春风不度玉门关。", "author": "王之涣", "cats": ["gushi", "bianSai", "siNian"]},
    {"text": "忽如一夜春风来，千树万树梨花开。", "author": "岑参", "cats": ["gushi", "meiLi", "dongTian"]},
    {"text": "瀚海阑干百丈冰，愁云惨淡万里凝。", "author": "岑参", "cats": ["gushi", "hanLeng", "tongKu"]},
    {"text": "接天莲叶无穷碧，映日荷花别样红。", "author": "杨万里", "cats": ["gushi", "meiLi", "xiaTian"]},
    {"text": "小荷才露尖尖角，早有蜻蜓立上头。", "author": "杨万里", "cats": ["gushi", "meiLi", "xiaTian"]},
    {"text": "停车坐爱枫林晚，霜叶红于二月花。", "author": "杜牧", "cats": ["gushi", "meiLi", "qiuTian"]},
    {"text": "远上寒山石径斜，白云生处有人家。", "author": "杜牧", "cats": ["gushi", "meiLi", "jingSe"]},
    {"text": "商女不知亡国恨，隔江犹唱后庭花。", "author": "杜牧", "cats": ["gushi", "aiGuo", "ganKai"]},
    {"text": "清明时节雨纷纷，路上行人欲断魂。", "author": "杜牧", "cats": ["gushi", "jieRi", "youShang"]},
    {"text": "千里莺啼绿映红，水村山郭酒旗风。", "author": "杜牧", "cats": ["gushi", "chunTian", "meiLi"]},
    {"text": "南朝四百八十寺，多少楼台烟雨中。", "author": "杜牧", "cats": ["gushi", "liShi", "jingSe"]},
    {"text": "天街小雨润如酥，草色遥看近却无。", "author": "韩愈", "cats": ["gushi", "chunTian", "meiLi"]},
    {"text": "最是一年春好处，绝胜烟柳满皇都。", "author": "韩愈", "cats": ["gushi", "chunTian", "meiLi"]},
    {"text": "千山鸟飞绝，万径人踪灭。", "author": "柳宗元", "cats": ["gushi", "dongTian", "guDu"]},
    {"text": "孤舟蓑笠翁，独钓寒江雪。", "author": "柳宗元", "cats": ["gushi", "dongTian", "guDu"]},
    {"text": "山重水复疑无路，柳暗花明又一村。", "author": "陆游", "cats": ["gushi", "mingYun", "xiWang"]},
    {"text": "夜阑卧听风吹雨，铁马冰河入梦来。", "author": "陆游", "cats": ["gushi", "aiGuo", "mengXiang"]},
    {"text": "小楼一夜听春雨，深巷明朝卖杏花。", "author": "陆游", "cats": ["gushi", "chunTian", "meiLi"]},
    {"text": "位卑未敢忘忧国，事定犹须待阖棺。", "author": "陆游", "cats": ["gushi", "aiGuo", "zeRen"]},
    {"text": "零落成泥碾作尘，只有香如故。", "author": "陆游", "cats": ["gushi", "pinGe", "jianChi"]},
    {"text": "暖风熏得游人醉，直把杭州作汴州。", "author": "林升", "cats": ["gushi", "fengCi", "aiGuo"]},
    {"text": "等闲识得东风面，万紫千红总是春。", "author": "朱熹", "cats": ["gushi", "chunTian", "meiLi"]},
    {"text": "半亩方塘一鉴开，天光云影共徘徊。", "author": "朱熹", "cats": ["gushi", "meiLi", "jingSe"]},
    {"text": "海上生明月，天涯共此时。", "author": "张九龄", "cats": ["gushi", "siNian", "youqing"]},
    {"text": "落霞与孤鹜齐飞，秋水共长天一色。", "author": "王勃", "cats": ["gushi", "meiLi", "zhuangGuan"]},
    {"text": "星垂平野阔，月涌大江流。", "author": "杜甫", "cats": ["gushi", "zhuangGuan", "jingSe"]},
    {"text": "无边落木萧萧下，不尽长江滚滚来。", "author": "杜甫", "cats": ["gushi", "qiuTian", "zhuangGuan"]},
    {"text": "烽火连三月，家书抵万金。", "author": "杜甫", "cats": ["gushi", "zhanzheng", "jiaTing"]},
    {"text": "感时花溅泪，恨别鸟惊心。", "author": "杜甫", "cats": ["gushi", "youShang", "aiGuo"]},
    {"text": "会当凌绝顶，一览众山小。", "author": "杜甫", "cats": ["gushi", "lizhi", "gaoDu"]},
    {"text": "随风潜入夜，润物细无声。", "author": "杜甫", "cats": ["gushi", "chunYu", "wuSheng"]},
    {"text": "野火烧不尽，春风吹又生。", "author": "白居易", "cats": ["gushi", "jianQiang", "shengMing"]},
    {"text": "日出江花红胜火，春来江水绿如蓝。", "author": "白居易", "cats": ["gushi", "chunTian", "meiLi"]},
    {"text": "在天愿作比翼鸟，在地愿为连理枝。", "author": "白居易", "cats": ["gushi", "aiqing", "mingren"]},
    {"text": "回眸一笑百媚生，六宫粉黛无颜色。", "author": "白居易", "cats": ["gushi", "meiLi", "nvXing"]},
    {"text": "千呼万唤始出来，犹抱琵琶半遮面。", "author": "白居易", "cats": ["gushi", "youShang", "nvXing"]},
    {"text": "大弦嘈嘈如急雨，小弦切切如私语。", "author": "白居易", "cats": ["gushi", "yinYue", "biYu"]},
    {"text": "别有幽愁暗恨生，此时无声胜有声。", "author": "白居易", "cats": ["gushi", "youShang", "wuSheng"]},
    {"text": "同是天涯沦落人，相逢何必曾相识。", "author": "白居易", "cats": ["gushi", "rensheng", "youqing"]},
    {"text": "座中泣下谁最多？江州司马青衫湿。", "author": "白居易", "cats": ["gushi", "youShang", "beiQing"]},
    {"text": "一道残阳铺水中，半江瑟瑟半江红。", "author": "白居易", "cats": ["gushi", "meiLi", "jingSe"]},
    {"text": "可怜九月初三夜，露似真珠月似弓。", "author": "白居易", "cats": ["gushi", "meiLi", "qiuTian"]},
    {"text": "空山不见人，但闻人语响。", "author": "王维", "cats": ["gushi", "jingSe", "youJing"]},
    {"text": "返景入深林，复照青苔上。", "author": "王维", "cats": ["gushi", "meiLi", "jingSe"]},
    {"text": "人闲桂花落，夜静春山空。", "author": "王维", "cats": ["gushi", "youJing", "meiLi"]},
    {"text": "月出惊山鸟，时鸣春涧中。", "author": "王维", "cats": ["gushi", "youJing", "meiLi"]},
    {"text": "深林人不知，明月来相照。", "author": "王维", "cats": ["gushi", "gudu", "mingYue"]},

    # ===== 成长 =====
    {"text": "成长是一场和自己的比赛，你要做的就是比昨天的自己更好一点。", "author": "佚名", "cats": ["chengzhang", "lizhi"]},
    {"text": "不要着急，最好的总会在最不经意的时候出现。", "author": "泰戈尔", "cats": ["chengzhang", "kuaile"]},
    {"text": "真正的成长，是学会与不完美的自己和解。", "author": "佚名", "cats": ["chengzhang", "zixin"]},
    {"text": "你若盛开，蝴蝶自来；你若精彩，天自安排。", "author": "佚名", "cats": ["chengzhang", "nuLi"]},
    {"text": "成长的过程就是不断发现自己以前是傻逼的过程。", "author": "佚名", "cats": ["chengzhang", "zhihui"]},
    {"text": "人之所以痛苦，在于追求错误的东西。", "author": "佚名", "cats": ["chengzhang", "tongku", "zhihui"]},
    {"text": "人生没有白走的路，每一步都算数。", "author": "佚名", "cats": ["chengzhang", "rensheng", "jingYan"]},
    {"text": "愿你出走半生，归来仍是少年。", "author": "佚名", "cats": ["chengzhang", "meihao", "benXin"]},
    {"text": "所有的胜利，与征服自己的胜利比起来，都是微不足道。", "author": "柏拉图", "cats": ["chengzhang", "zixin", "chenggong"]},
    {"text": "最大的挑战和突破在于用人，而用人最大的突破在于信任人。", "author": "马云", "cats": ["chengzhang", "guanli", "mingren"]},
    {"text": "今天很残酷，明天更残酷，后天很美好，但绝对大部分是死在明天晚上。", "author": "马云", "cats": ["chengzhang", "jianchi", "mingren"]},
    {"text": "你今天的苦果，是昨天的伏笔；当下的付出，是明日的花开。", "author": "佚名", "cats": ["chengzhang", "jianchi", "chuShi"]},
    {"text": "生活不是等待风暴过去，而是学会在雨中跳舞。", "author": "维维安·格林", "cats": ["chengzhang", "yongqi", "kuaile"]},
    {"text": "成长就是把哭声调成静音的过程。", "author": "佚名", "cats": ["chengzhang", "jianqiang", "chengShu"]},
    {"text": "使人成熟的是经历，而不是岁月。", "author": "佚名", "cats": ["chengzhang", "jingYan", "chengShu"]},
    {"text": "你要悄悄拔尖，然后惊艳所有人。", "author": "佚名", "cats": ["chengzhang", "nuLi", "youXiu"]},
    {"text": "别让任何人打乱你的人生节奏。", "author": "佚名", "cats": ["chengzhang", "ziXin", "jieZou"]},
    {"text": "你要偷偷努力，然后成为别人的梦想。", "author": "佚名", "cats": ["chengzhang", "nuLi", "mengXiang"]},
    {"text": "熬得住就出众，熬不住就出局。", "author": "佚名", "cats": ["chengzhang", "jianchi", "jingZheng"]},
    {"text": "你可以哭，但不能输。", "author": "佚名", "cats": ["chengzhang", "jianqiang", "yongqi"]},

    # ===== 梦想 =====
    {"text": "梦想还是要有的，万一实现了呢？", "author": "马云", "cats": ["mengxiang", "mingren", "lizhi"]},
    {"text": "世界上最快乐的事，莫过于为理想而奋斗。", "author": "苏格拉底", "cats": ["mengxiang", "kuaile", "lizhi"]},
    {"text": "一个人的理想越崇高，生活越纯洁。", "author": "伏尼契", "cats": ["mengxiang", "rensheng"]},
    {"text": "人的活动如果没有理想的鼓舞，就会变得空虚而渺小。", "author": "车尔尼雪夫斯基", "cats": ["mengxiang", "lizhi"]},
    {"text": "我梦想有一天，这个国家会站立起来，真正实现其信条的真谛。", "author": "马丁·路德·金", "cats": ["mengxiang", "mingren"]},
    {"text": "不要只因一次失败，就放弃你原来决心想达到的目的。", "author": "莎士比亚", "cats": ["mengxiang", "shibai", "jianchi"]},
    {"text": "志当存高远。", "author": "诸葛亮", "cats": ["mengxiang", "lizhi", "gushi"]},
    {"text": "非淡泊无以明志，非宁静无以致远。", "author": "诸葛亮", "cats": ["mengxiang", "gushi", "xinjing"]},
    {"text": "为中华之崛起而读书。", "author": "周恩来", "cats": ["mengxiang", "xuexi", "mingren"]},
    {"text": "理想是指路明灯。没有理想，就没有坚定的方向。", "author": "托尔斯泰", "cats": ["mengxiang", "lizhi"]},
    {"text": "生活中没有理想的人，是可怜的。", "author": "屠格涅夫", "cats": ["mengxiang", "rensheng"]},
    {"text": "人生最高之理想，在求达于真理。", "author": "李大钊", "cats": ["mengxiang", "zhenLi", "mingren"]},
    {"text": "不想当将军的士兵不是好士兵。", "author": "拿破仑", "cats": ["mengxiang", "lizhi", "mingren"]},
    {"text": "老骥伏枥，志在千里；烈士暮年，壮心不已。", "author": "曹操", "cats": ["mengxiang", "lizhi", "gushi"]},
    {"text": "穷且益坚，不坠青云之志。", "author": "王勃", "cats": ["mengxiang", "jianchi", "gushi"]},
    {"text": "燕雀安知鸿鹄之志哉！", "author": "陈涉", "cats": ["mengxiang", "lizhi", "mingren"]},
    {"text": "大鹏一日同风起，扶摇直上九万里。", "author": "李白", "cats": ["mengxiang", "lizhi", "gushi"]},
    {"text": "长风破浪会有时，直挂云帆济沧海。", "author": "李白", "cats": ["mengxiang", "lizhi", "gushi"]},
    {"text": "俱怀逸兴壮思飞，欲上青天揽明月。", "author": "李白", "cats": ["mengxiang", "lizhi", "gushi"]},
    {"text": "会当凌绝顶，一览众山小。", "author": "杜甫", "cats": ["mengxiang", "lizhi", "gushi"]},

    # ===== 时间 =====
    {"text": "一寸光阴一寸金，寸金难买寸光阴。", "author": "古训", "cats": ["shijian", "zhenXi", "gushi"]},
    {"text": "盛年不重来，一日难再晨。", "author": "陶渊明", "cats": ["shijian", "zhenXi", "gushi"]},
    {"text": "及时当勉励，岁月不待人。", "author": "陶渊明", "cats": ["shijian", "lizhi", "gushi"]},
    {"text": "逝者如斯夫，不舍昼夜。", "author": "孔子", "cats": ["shijian", "gushi", "gankai"]},
    {"text": "时间就像海绵里的水，只要愿挤，总还是有的。", "author": "鲁迅", "cats": ["shijian", "mingren"]},
    {"text": "你热爱生命吗？那么别浪费时间，因为时间是组成生命的材料。", "author": "富兰克林", "cats": ["shijian", "shengMing"]},
    {"text": "世界上最快而又最慢，最长而又最短，最平凡而又最珍贵的就是时间。", "author": "高尔基", "cats": ["shijian", "zhenXi"]},
    {"text": "时间是最公平合理的，它从不多给谁一份。", "author": "高尔基", "cats": ["shijian", "gongPing"]},
    {"text": "不要为已消尽之年华叹息，必须正视匆匆溜走的时光。", "author": "布莱希特", "cats": ["shijian", "yongqi"]},
    {"text": "在所有的批评家中，最伟大、最正确、最天才的是时间。", "author": "别林斯基", "cats": ["shijian", "zhihui"]},
    {"text": "年华一去不复返，事业放弃在难成。", "author": "佚名", "cats": ["shijian", "shiye"]},
    {"text": "少壮不努力，老大徒伤悲。", "author": "汉乐府", "cats": ["shijian", "lizhi", "gushi"]},
    {"text": "黑发不知勤学早，白首方悔读书迟。", "author": "颜真卿", "cats": ["shijian", "xuexi", "gushi"]},
    {"text": "莫等闲，白了少年头，空悲切。", "author": "岳飞", "cats": ["shijian", "lizhi", "gushi"]},
    {"text": "人生天地之间，若白驹过隙，忽然而已。", "author": "庄子", "cats": ["shijian", "rensheng", "gushi"]},
    {"text": "年年岁岁花相似，岁岁年年人不同。", "author": "刘希夷", "cats": ["shijian", "rensheng", "gushi"]},
    {"text": "江畔何人初见月？江月何年初照人？", "author": "张若虚", "cats": ["shijian", "rensheng", "gushi"]},
    {"text": "人生代代无穷已，江月年年只相似。", "author": "张若虚", "cats": ["shijian", "rensheng", "gushi"]},
    {"text": "前不见古人，后不见来者。", "author": "陈子昂", "cats": ["shijian", "gushi", "gudu"]},
    {"text": "念天地之悠悠，独怆然而涕下。", "author": "陈子昂", "cats": ["shijian", "gushi", "beiZhuang"]},

    # ===== 坚持 =====
    {"text": "锲而舍之，朽木不折；锲而不舍，金石可镂。", "author": "荀子", "cats": ["jianchi", "lizhi", "gushi"]},
    {"text": "千里之行，始于足下。", "author": "老子", "cats": ["jianchi", "lizhi", "gushi"]},
    {"text": "不积跬步，无以至千里；不积小流，无以成江海。", "author": "荀子", "cats": ["jianchi", "lizhi", "gushi"]},
    {"text": "只要功夫深，铁杵磨成针。", "author": "古训", "cats": ["jianchi", "lizhi"]},
    {"text": "滴水能把石穿透，万事功到自然成。", "author": "古训", "cats": ["jianchi", "chenggong"]},
    {"text": "成功的秘诀，在永不改变既定的目的。", "author": "卢梭", "cats": ["jianchi", "chenggong"]},
    {"text": "伟大的作品不是靠力量，而是靠坚持来完成的。", "author": "约翰逊", "cats": ["jianchi", "chenggong"]},
    {"text": "要从容地着手去做一件事，但一旦开始，就要坚持到底。", "author": "比阿斯", "cats": ["jianchi", "yongqi"]},
    {"text": "不经一番寒彻骨，怎得梅花扑鼻香。", "author": "黄蘖禅师", "cats": ["jianchi", "tongku", "gushi"]},
    {"text": "宝剑锋从磨砺出，梅花香自苦寒来。", "author": "古训", "cats": ["jianchi", "tongku", "lizhi"]},
    {"text": "坚持意志伟大的事业需要始终不渝的精神。", "author": "伏尔泰", "cats": ["jianchi", "shiye"]},
    {"text": "最可怕的敌人，就是没有坚强的信念。", "author": "罗曼·罗兰", "cats": ["jianchi", "zixin", "lizhi"]},
    {"text": "咬定青山不放松，立根原在破岩中。", "author": "郑板桥", "cats": ["jianchi", "lizhi", "gushi"]},
    {"text": "千磨万击还坚劲，任尔东西南北风。", "author": "郑板桥", "cats": ["jianchi", "lizhi", "gushi"]},
    {"text": "世上无难事，只怕有心人。", "author": "古训", "cats": ["jianchi", "lizhi"]},
    {"text": "世上无难事，只要肯登攀。", "author": "毛泽东", "cats": ["jianchi", "lizhi", "mingren"]},
    {"text": "雄关漫道真如铁，而今迈步从头越。", "author": "毛泽东", "cats": ["jianchi", "lizhi", "mingren"]},
    {"text": "不到长城非好汉，屈指行程二万。", "author": "毛泽东", "cats": ["jianchi", "lizhi", "mingren"]},
    {"text": "吾志所向，一往无前，愈挫愈奋，再接再厉。", "author": "孙中山", "cats": ["jianchi", "lizhi", "mingren"]},
    {"text": "革命尚未成功，同志仍需努力。", "author": "孙中山", "cats": ["jianchi", "lizhi", "mingren"]},

    # ===== 友情 =====
    {"text": "海内存知己，天涯若比邻。", "author": "王勃", "cats": ["youqing", "gushi", "liuxue"]},
    {"text": "莫愁前路无知己，天下谁人不识君。", "author": "高适", "cats": ["youqing", "liuxue", "gushi"]},
    {"text": "桃花潭水深千尺，不及汪伦送我情。", "author": "李白", "cats": ["youqing", "gushi"]},
    {"text": "劝君更尽一杯酒，西出阳关无故人。", "author": "王维", "cats": ["youqing", "liuxue", "gushi"]},
    {"text": "有朋自远方来，不亦乐乎？", "author": "孔子", "cats": ["youqing", "kuaile", "gushi"]},
    {"text": "朋友是生活中的阳光。", "author": "易卜生", "cats": ["youqing", "kuaile"]},
    {"text": "真正的友谊既能容忍朋友提出的劝告，又有使自己接受劝告。", "author": "西塞罗", "cats": ["youqing", "zhihui"]},
    {"text": "友谊永远是一个甜柔的责任，从来不是一种机会。", "author": "纪伯伦", "cats": ["youqing", "zhenCheng"]},
    {"text": "世间最美好的东西，莫过于有几个头脑和心地都很正直的朋友。", "author": "爱因斯坦", "cats": ["youqing", "meihao", "mingren"]},
    {"text": "患难识朋友。", "author": "列宁", "cats": ["youqing", "tongku"]},
    {"text": "兄弟可能不是朋友，但朋友常常如兄弟。", "author": "富兰克林", "cats": ["youqing", "jiaoting"]},
    {"text": "人生最美好的东西，就是他同别人的友谊。", "author": "林肯", "cats": ["youqing", "meihao", "rensheng"]},
    {"text": "同是天涯沦落人，相逢何必曾相识。", "author": "白居易", "cats": ["youqing", "rensheng", "gushi"]},
    {"text": "相逢何必曾相识，同是天涯沦落人。", "author": "白居易", "cats": ["youqing", "rensheng", "gushi"]},
    {"text": "人生贵相知，何用金与钱。", "author": "李白", "cats": ["youqing", "gushi", "zhenGui"]},
    {"text": "故人西辞黄鹤楼，烟花三月下扬州。", "author": "李白", "cats": ["youqing", "liuxue", "gushi"]},
    {"text": "孤帆远影碧空尽，唯见长江天际流。", "author": "李白", "cats": ["youqing", "liuxue", "gushi"]},
    {"text": "浮云游子意，落日故人情。", "author": "李白", "cats": ["youqing", "liuxue", "gushi"]},
    {"text": "挥手自兹去，萧萧班马鸣。", "author": "李白", "cats": ["youqing", "liuxue", "gushi"]},
    {"text": "正是江南好风景，落花时节又逢君。", "author": "杜甫", "cats": ["youqing", "gushi", "chongFeng"]},

    # ===== 智慧/哲理 =====
    {"text": "祸兮福之所倚，福兮祸之所伏。", "author": "老子", "cats": ["zhihui", "rensheng", "gushi"]},
    {"text": "知人者智，自知者明。", "author": "老子", "cats": ["zhihui", "zixin", "gushi"]},
    {"text": "上善若水，水善利万物而不争。", "author": "老子", "cats": ["zhihui", "pinDe", "gushi"]},
    {"text": "千里之堤，溃于蚁穴。", "author": "韩非子", "cats": ["zhihui", "xiJie", "gushi"]},
    {"text": "塞翁失马，焉知非福。", "author": "淮南子", "cats": ["zhihui", "rensheng", "gushi"]},
    {"text": "失之东隅，收之桑榆。", "author": "后汉书", "cats": ["zhihui", "rensheng", "gushi"]},
    {"text": "尺有所短，寸有所长。", "author": "楚辞", "cats": ["zhihui", "qianXu", "gushi"]},
    {"text": "物以类聚，人以群分。", "author": "易经", "cats": ["zhihui", "renJi", "gushi"]},
    {"text": "满招损，谦受益。", "author": "尚书", "cats": ["zhihui", "qianXu", "gushi"]},
    {"text": "业精于勤荒于嬉，行成于思毁于随。", "author": "韩愈", "cats": ["zhihui", "xuexi", "gushi"]},
    {"text": "山重水复疑无路，柳暗花明又一村。", "author": "陆游", "cats": ["zhihui", "mingYun", "gushi"]},
    {"text": "不识庐山真面目，只缘身在此山中。", "author": "苏轼", "cats": ["zhihui", "shiJiao", "gushi"]},
    {"text": "欲穷千里目，更上一层楼。", "author": "王之涣", "cats": ["zhihui", "jinBu", "gushi"]},
    {"text": "问渠那得清如许，为有源头活水来。", "author": "朱熹", "cats": ["zhihui", "xuexi", "gushi"]},
    {"text": "纸上得来终觉浅，绝知此事要躬行。", "author": "陆游", "cats": ["zhihui", "shiJian", "gushi"]},
    {"text": "知之为知之，不知为不知，是知也。", "author": "孔子", "cats": ["zhihui", "xuexi", "gushi"]},
    {"text": "学而不思则罔，思而不学则殆。", "author": "孔子", "cats": ["zhihui", "xuexi", "gushi"]},
    {"text": "三人行，必有我师焉。", "author": "孔子", "cats": ["zhihui", "qianXu", "gushi"]},
    {"text": "知识就是力量。", "author": "培根", "cats": ["zhihui", "xuexi", "mingren"]},
    {"text": "智慧意味着以最佳的方式追求最高的目标。", "author": "大哈奇森", "cats": ["zhihui", "muBiao"]},

    # ===== 家庭/亲情 =====
    {"text": "谁言寸草心，报得三春晖。", "author": "孟郊", "cats": ["jiaoting", "ganen", "gushi"]},
    {"text": "慈母手中线，游子身上衣。", "author": "孟郊", "cats": ["jiaoting", "ganen", "gushi"]},
    {"text": "临行密密缝，意恐迟迟归。", "author": "孟郊", "cats": ["jiaoting", "ganen", "gushi"]},
    {"text": "鸦有反哺之义，羊有跪乳之恩。", "author": "古训", "cats": ["jiaoting", "ganen", "gushi"]},
    {"text": "滴水之恩，当涌泉相报。", "author": "古训", "cats": ["jiaoting", "ganen", "gushi"]},
    {"text": "父母之恩，水不能溺，火不能灭。", "author": "俄国谚语", "cats": ["jiaoting", "ganen"]},
    {"text": "人世间最美丽的情景是出现在当我们怀念到母亲的时候。", "author": "莫泊桑", "cats": ["jiaoting", "meihao", "muQin"]},
    {"text": "百善孝为先。", "author": "古训", "cats": ["jiaoting", "xiaoShun", "gushi"]},
    {"text": "子欲养而亲不待，树欲静而风不止。", "author": "古训", "cats": ["jiaoting", "ganen", "gushi"]},
    {"text": "家和万事兴。", "author": "古训", "cats": ["jiaoting", "heXie", "gushi"]},
    {"text": "一家人能够相互密切合作，才是世界上唯一的真正幸福。", "author": "居里夫人", "cats": ["jiaoting", "xingfu"]},
    {"text": "家是世界上唯一隐藏人类缺点与失败的地方。", "author": "萧伯纳", "cats": ["jiaoting", "wenNuan"]},
    {"text": "幸福的家庭都是相似的，不幸的家庭各有各的不幸。", "author": "托尔斯泰", "cats": ["jiaoting", "xingfu"]},
    {"text": "父母之所爱亦爱之，父母之所敬亦敬之。", "author": "孔子", "cats": ["jiaoting", "xiaoShun", "gushi"]},
    {"text": "一粥一饭当思来处不易，半丝半缕恒念物力维艰。", "author": "朱柏庐", "cats": ["jiaoting", "jieYue", "gushi"]},
    {"text": "独在异乡为异客，每逢佳节倍思亲。", "author": "王维", "cats": ["jiaoting", "xiangChou", "gushi"]},
    {"text": "烽火连三月，家书抵万金。", "author": "杜甫", "cats": ["jiaoting", "zhanZheng", "gushi"]},
    {"text": "露从今夜白，月是故乡明。", "author": "杜甫", "cats": ["jiaoting", "xiangChou", "gushi"]},
    {"text": "举头望明月，低头思故乡。", "author": "李白", "cats": ["jiaoting", "xiangChou", "gushi"]},
    {"text": "此夜曲中闻折柳，何人不起故园情。", "author": "李白", "cats": ["jiaoting", "xiangChou", "gushi"]},

    # ===== 快乐/幸福 =====
    {"text": "知足者常乐。", "author": "古训", "cats": ["kuaile", "xingfu", "gushi"]},
    {"text": "人生得意须尽欢，莫使金樽空对月。", "author": "李白", "cats": ["kuaile", "rensheng", "gushi"]},
    {"text": "快乐不在于事情，而在于我们自己。", "author": "理查德·瓦格纳", "cats": ["kuaile", "xinJing"]},
    {"text": "世界上最快乐的事，莫过于为理想而奋斗。", "author": "苏格拉底", "cats": ["kuaile", "mengxiang", "lizhi"]},
    {"text": "真正的快乐是内在的，它只有在人类的心灵里才能发现。", "author": "布雷默", "cats": ["kuaile", "xinLing"]},
    {"text": "所谓内心的快乐，是一个人过着健全的、正常的、和谐的生活所感到的快乐。", "author": "罗曼·罗兰", "cats": ["kuaile", "heXie"]},
    {"text": "笑是一种没有副作用的镇静剂。", "author": "格拉索", "cats": ["kuaile", "jiankang"]},
    {"text": "快乐是一种心境，跟财富、年龄与环境无关。", "author": "佚名", "cats": ["kuaile", "xinJing"]},
    {"text": "把脸迎向阳光，那就不会有阴影。", "author": "海伦·凯勒", "cats": ["kuaile", "yongqi"]},
    {"text": "生活中不是缺少美，而是缺少发现美的眼睛。", "author": "罗丹", "cats": ["kuaile", "meiLi", "mingren"]},
    {"text": "采菊东篱下，悠然见南山。", "author": "陶渊明", "cats": ["kuaile", "xianYi", "gushi"]},
    {"text": "久旱逢甘雨，他乡遇故知。", "author": "汪洙", "cats": ["kuaile", "xingFu", "gushi"]},
    {"text": "洞房花烛夜，金榜题名时。", "author": "汪洙", "cats": ["kuaile", "xingFu", "gushi"]},
    {"text": "春宵一刻值千金。", "author": "苏轼", "cats": ["kuaile", "meihao", "gushi"]},
    {"text": "人逢喜事精神爽，月到中秋分外明。", "author": "古训", "cats": ["kuaile", "xingFu", "gushi"]},
    {"text": "笑一笑，十年少；愁一愁，白了头。", "author": "古训", "cats": ["kuaile", "jiankang", "gushi"]},
    {"text": "乐人之乐，人亦乐其乐；忧人之忧，人亦忧其忧。", "author": "白居易", "cats": ["kuaile", "xiangHu", "gushi"]},
    {"text": "先天下之忧而忧，后天下之乐而乐。", "author": "范仲淹", "cats": ["kuaile", "aiGuo", "gushi"]},
    {"text": "不以物喜，不以己悲。", "author": "范仲淹", "cats": ["kuaile", "xinJing", "gushi"]},
    {"text": "心旷神怡，宠辱偕忘。", "author": "范仲淹", "cats": ["kuaile", "ziYou", "gushi"]},

    # ===== 名人名言 =====
    {"text": "横眉冷对千夫指，俯首甘为孺子牛。", "author": "鲁迅", "cats": ["mingren", "pinGe", "rensheng"]},
    {"text": "其实地上本没有路，走的人多了，也便成了路。", "author": "鲁迅", "cats": ["mingren", "chuangZao", "rensheng"]},
    {"text": "时间就像海绵里的水，只要愿挤，总还是有的。", "author": "鲁迅", "cats": ["mingren", "shijian"]},
    {"text": "不在沉默中爆发，就在沉默中灭亡。", "author": "鲁迅", "cats": ["mingren", "yongQi", "fenDou"]},
    {"text": "真的猛士，敢于直面惨淡的人生，敢于正视淋漓的鲜血。", "author": "鲁迅", "cats": ["mingren", "yongQi", "jianQiang"]},
    {"text": "无情未必真豪杰，怜子如何不丈夫。", "author": "鲁迅", "cats": ["mingren", "qingGan", "zhangFu"]},
    {"text": "人生最痛苦的是梦醒了无路可走。", "author": "鲁迅", "cats": ["mingren", "tongKu", "rensheng"]},
    {"text": "哪里有天才，我是把别人喝咖啡的工夫都用在了工作上。", "author": "鲁迅", "cats": ["mingren", "nuLi", "gongZuo"]},
    {"text": "我好像是一只牛，吃的是草，挤出的是奶。", "author": "鲁迅", "cats": ["mingren", "fengXian", "pinGe"]},
    {"text": "希望是附丽于存在的，有存在，便有希望，有希望，便是光明。", "author": "鲁迅", "cats": ["mingren", "xiWang", "guangMing"]},
    {"text": "俱往矣，数风流人物，还看今朝。", "author": "毛泽东", "cats": ["mingren", "haoQing", "gushi"]},
    {"text": "世上无难事，只要肯登攀。", "author": "毛泽东", "cats": ["mingren", "jianChi", "lizhi"]},
    {"text": "雄关漫道真如铁，而今迈步从头越。", "author": "毛泽东", "cats": ["mingren", "jianChi", "lizhi"]},
    {"text": "不到长城非好汉，屈指行程二万。", "author": "毛泽东", "cats": ["mingren", "jianChi", "lizhi"]},
    {"text": "为中华之崛起而读书。", "author": "周恩来", "cats": ["mingren", "mengXiang", "xueXi"]},
    {"text": "吾志所向，一往无前，愈挫愈奋，再接再厉。", "author": "孙中山", "cats": ["mingren", "jianChi", "lizhi"]},
    {"text": "革命尚未成功，同志仍需努力。", "author": "孙中山", "cats": ["mingren", "jianChi", "lizhi"]},
    {"text": "人不可有傲气，但不可无傲骨。", "author": "徐悲鸿", "cats": ["mingren", "zixin", "pinGe"]},
    {"text": "苟利国家生死以，岂因祸福避趋之。", "author": "林则徐", "cats": ["mingren", "aiGuo", "gushi"]},
    {"text": "海纳百川，有容乃大；壁立千仞，无欲则刚。", "author": "林则徐", "cats": ["mingren", "daode", "gushi"]},

    # ===== 道德/品格 =====
    {"text": "勿以恶小而为之，勿以善小而不为。", "author": "刘备", "cats": ["daode", "xingWei", "gushi"]},
    {"text": "君子坦荡荡，小人长戚戚。", "author": "孔子", "cats": ["daode", "junzi", "gushi"]},
    {"text": "富贵不能淫，贫贱不能移，威武不能屈。", "author": "孟子", "cats": ["daode", "jianChi", "gushi"]},
    {"text": "出淤泥而不染，濯清涟而不妖。", "author": "周敦颐", "cats": ["daode", "gaoShang", "gushi"]},
    {"text": "先天下之忧而忧，后天下之乐而乐。", "author": "范仲淹", "cats": ["daode", "aiGuo", "gushi"]},
    {"text": "人生自古谁无死，留取丹心照汗青。", "author": "文天祥", "cats": ["daode", "aiGuo", "gushi"]},
    {"text": "粉骨碎身浑不怕，要留清白在人间。", "author": "于谦", "cats": ["daode", "qingBai", "gushi"]},
    {"text": "静以修身，俭以养德。", "author": "诸葛亮", "cats": ["daode", "xiuShen", "gushi"]},
    {"text": "非淡泊无以明志，非宁静无以致远。", "author": "诸葛亮", "cats": ["daode", "mengXiang", "gushi"]},
    {"text": "鞠躬尽瘁，死而后已。", "author": "诸葛亮", "cats": ["daode", "fengXian", "gushi"]},
    {"text": "道德是真理之花。", "author": "雨果", "cats": ["daode", "zhenLi"]},
    {"text": "最高的道德就是不断地为人服务，为人类的爱而工作。", "author": "甘地", "cats": ["daode", "fuWu"]},
    {"text": "美德大都包含在良好的习惯之内。", "author": "帕利克", "cats": ["daode", "xiGuan"]},
    {"text": "人而无信，不知其可也。", "author": "孔子", "cats": ["daode", "chengXin", "gushi"]},
    {"text": "言必信，行必果。", "author": "孔子", "cats": ["daode", "chengXin", "gushi"]},
    {"text": "己所不欲，勿施于人。", "author": "孔子", "cats": ["daode", "xiangHu", "gushi"]},
    {"text": "君子成人之美，不成人之恶。", "author": "孔子", "cats": ["daode", "junzi", "gushi"]},
    {"text": "穷则独善其身，达则兼善天下。", "author": "孟子", "cats": ["daode", "renSheng", "gushi"]},
    {"text": "生，亦我所欲也；义，亦我所欲也。二者不可得兼，舍生而取义者也。", "author": "孟子", "cats": ["daode", "yiQi", "gushi"]},
    {"text": "吾善养吾浩然之气。", "author": "孟子", "cats": ["daode", "xiuShen", "gushi"]},

    # ===== 成功 =====
    {"text": "成功的秘诀，在永不改变既定的目的。", "author": "卢梭", "cats": ["chenggong", "jianchi"]},
    {"text": "失败是成功之母。", "author": "古训", "cats": ["chenggong", "shibai"]},
    {"text": "天才是百分之一的灵感加百分之九十九的汗水。", "author": "爱迪生", "cats": ["chenggong", "gongzuo", "mingren"]},
    {"text": "成功=艰苦的劳动+正确的方法+少说空话。", "author": "爱因斯坦", "cats": ["chenggong", "gongZuo", "mingren"]},
    {"text": "最困难之时，就是离成功不远之日。", "author": "拿破仑", "cats": ["chenggong", "kunNan", "mingren"]},
    {"text": "成功的唯一秘诀——坚持最后一分钟。", "author": "柏拉图", "cats": ["chenggong", "jianchi"]},
    {"text": "如果你希望成功，当以恒心为良友，以经验为参谋。", "author": "爱迪生", "cats": ["chenggong", "hengXin"]},
    {"text": "人生伟业的建立，不在能知，乃在能行。", "author": "赫胥黎", "cats": ["chenggong", "xingDong"]},
    {"text": "成功不是将来才有的，而是从决定去做的那一刻起，持续累积而成。", "author": "佚名", "cats": ["chenggong", "leiJi"]},
    {"text": "胜利者往往是从坚持最后五分钟的时间中得来成功。", "author": "牛顿", "cats": ["chenggong", "jianchi", "mingren"]},
    {"text": "成功=目标+行动+坚持。", "author": "佚名", "cats": ["chenggong", "jianchi", "muBiao"]},
    {"text": "成功的人找方法，失败的人找借口。", "author": "佚名", "cats": ["chenggong", "fangFa", "shiBai"]},
    {"text": "机会只偏爱有准备的头脑。", "author": "巴斯德", "cats": ["chenggong", "jiHui", "zhunBei"]},
    {"text": "成功的道路上充满荆棘，只有勇敢的人才能通过。", "author": "佚名", "cats": ["chenggong", "yongQi", "kunNan"]},
    {"text": "世上无难事，只怕有心人。", "author": "古训", "cats": ["chenggong", "jianchi", "lizhi"]},
    {"text": "只要功夫深，铁杵磨成针。", "author": "古训", "cats": ["chenggong", "jianchi"]},
    {"text": "滴水能把石穿透，万事功到自然成。", "author": "古训", "cats": ["chenggong", "jianchi"]},
    {"text": "宝剑锋从磨砺出，梅花香自苦寒来。", "author": "古训", "cats": ["chenggong", "jianchi", "tongKu"]},
    {"text": "吃得苦中苦，方为人上人。", "author": "古训", "cats": ["chenggong", "tongKu", "lizhi"]},
    {"text": "不经一番寒彻骨，怎得梅花扑鼻香。", "author": "黄蘖禅师", "cats": ["chenggong", "jianchi", "gushi"]},

    # ===== 失败/挫折 =====
    {"text": "失败是成功之母。", "author": "古训", "cats": ["shibai", "chenggong"]},
    {"text": "不要只因一次失败，就放弃你原来决心想达到的目的。", "author": "莎士比亚", "cats": ["shibai", "mengxiang", "jianchi"]},
    {"text": "人生最大的荣耀不在于从不跌倒，而在于每次跌倒后都爬起来。", "author": "纳尔逊·曼德拉", "cats": ["shibai", "jianchi", "rensheng"]},
    {"text": "失败也是我需要的，它和成功对我一样有价值。", "author": "爱迪生", "cats": ["shibai", "jiazhi", "mingren"]},
    {"text": "苦难是人生的老师。", "author": "巴尔扎克", "cats": ["shibai", "chengzhang", "mingren"]},
    {"text": "最困难之时，就是离成功不远之日。", "author": "拿破仑", "cats": ["shibai", "chenggong", "mingren"]},
    {"text": "所有的胜利，与征服自己的胜利比起来，都是微不足道。", "author": "柏拉图", "cats": ["shibai", "zixin", "chenggong"]},
    {"text": "人不是为失败而生的，一个人可以被毁灭，但不能被打败。", "author": "海明威", "cats": ["shibai", "jianqiang"]},
    {"text": "故天将降大任于是人也，必先苦其心志，劳其筋骨。", "author": "孟子", "cats": ["shibai", "lizhi", "gushi"]},
    {"text": "宝剑锋从磨砺出，梅花香自苦寒来。", "author": "古训", "cats": ["shibai", "jianchi", "lizhi"]},
    {"text": "不经一番寒彻骨，怎得梅花扑鼻香。", "author": "黄蘖禅师", "cats": ["shibai", "jianchi", "gushi"]},
    {"text": "千磨万击还坚劲，任尔东西南北风。", "author": "郑板桥", "cats": ["shibai", "jianchi", "gushi"]},
    {"text": "咬定青山不放松，立根原在破岩中。", "author": "郑板桥", "cats": ["shibai", "jianchi", "gushi"]},
    {"text": "山重水复疑无路，柳暗花明又一村。", "author": "陆游", "cats": ["shibai", "xiWang", "gushi"]},
    {"text": "长风破浪会有时，直挂云帆济沧海。", "author": "李白", "cats": ["shibai", "mengXiang", "gushi"]},
    {"text": "天生我材必有用，千金散尽还复来。", "author": "李白", "cats": ["shibai", "zixin", "gushi"]},
    {"text": "世上无难事，只怕有心人。", "author": "古训", "cats": ["shibai", "jianchi"]},
    {"text": "塞翁失马，焉知非福。", "author": "淮南子", "cats": ["shibai", "zhihui", "gushi"]},
    {"text": "失之东隅，收之桑榆。", "author": "后汉书", "cats": ["shibai", "zhihui", "gushi"]},
    {"text": "野火烧不尽，春风吹又生。", "author": "白居易", "cats": ["shibai", "jianQiang", "gushi"]},

    # ===== 自信 =====
    {"text": "天生我材必有用，千金散尽还复来。", "author": "李白", "cats": ["zixin", "lizhi", "gushi"]},
    {"text": "自信是成功的第一秘诀。", "author": "爱默生", "cats": ["zixin", "chenggong", "mingren"]},
    {"text": "先相信你自己，然后别人才会相信你。", "author": "屠格涅夫", "cats": ["zixin", "rensheng"]},
    {"text": "有信心的人，可以化渺小为伟大，化平庸为神奇。", "author": "萧伯纳", "cats": ["zixin", "shenqi"]},
    {"text": "坚决的信心，能使平凡的人们，做出惊人的事业。", "author": "马尔顿", "cats": ["zixin", "shiye"]},
    {"text": "自信与骄傲有异；自信者常沉着，而骄傲者常浮扬。", "author": "梁启超", "cats": ["zixin", "qianxu"]},
    {"text": "恢弘志士之气，不宜妄自菲薄。", "author": "诸葛亮", "cats": ["zixin", "lizhi", "gushi"]},
    {"text": "仰天大笑出门去，我辈岂是蓬蒿人。", "author": "李白", "cats": ["zixin", "lizhi", "gushi"]},
    {"text": "安能摧眉折腰事权贵，使我不得开心颜！", "author": "李白", "cats": ["zixin", "zunYan", "gushi"]},
    {"text": "人不可有傲气，但不可无傲骨。", "author": "徐悲鸿", "cats": ["zixin", "pinGe", "mingren"]},
    {"text": "对于凌驾命运之上的人来说，信心就是生命的主宰。", "author": "海伦·凯勒", "cats": ["zixin", "mingYun"]},
    {"text": "你若盛开，蝴蝶自来；你若精彩，天自安排。", "author": "佚名", "cats": ["zixin", "nuLi", "chengZhang"]},
    {"text": "真正的成长，是学会与不完美的自己和解。", "author": "佚名", "cats": ["zixin", "chengZhang"]},
    {"text": "别让任何人打乱你的人生节奏。", "author": "佚名", "cats": ["zixin", "chengZhang", "jieZou"]},
    {"text": "你要悄悄拔尖，然后惊艳所有人。", "author": "佚名", "cats": ["zixin", "nuLi", "chengZhang"]},
    {"text": "地球上的任何一点离太阳都同样地遥远。", "author": "伯顿", "cats": ["zixin", "gongPing"]},
    {"text": "我们对自己抱有的信心，将使别人对我们萌生信心的绿芽。", "author": "拉劳士福古", "cats": ["zixin", "yingXiang"]},
    {"text": "除了人格以外，人生最大的损失，莫过于失掉自信心了。", "author": "培尔辛", "cats": ["zixin", "rensheng"]},
    {"text": "知人者智，自知者明。", "author": "老子", "cats": ["zixin", "zhihui", "gushi"]},
    {"text": "人贵在有自知之明。", "author": "古训", "cats": ["zixin", "zhihui", "gushi"]},

    # ===== 勇气 =====
    {"text": "勇敢里面有天才、力量和魔法。", "author": "歌德", "cats": ["yongqi", "zhihui"]},
    {"text": "勇气是衡量灵魂大小的标准。", "author": "卡耐基", "cats": ["yongqi", "linghun"]},
    {"text": "世界上只有一种真正的英雄主义，那就是在认清生活的真相后依然热爱生活。", "author": "罗曼·罗兰", "cats": ["yongqi", "rensheng", "kuaile"]},
    {"text": "真正的勇气不是无畏，而是带着恐惧前行。", "author": "佚名", "cats": ["yongqi", "chengzhang"]},
    {"text": "勇气是人类最重要的一种特质，倘若有了勇气，人类其他的特质自然也就具备了。", "author": "丘吉尔", "cats": ["yongqi", "tezhi"]},
    {"text": "大胆点，伟大的力量会来帮助你的。", "author": "爱默生", "cats": ["yongqi", "lizhi"]},
    {"text": "匹夫见辱，拔剑而起，挺身而斗，此不足为勇也。", "author": "苏轼", "cats": ["yongqi", "gushi", "zhiHui"]},
    {"text": "天下有大勇者，猝然临之而不惊，无故加之而不怒。", "author": "苏轼", "cats": ["yongqi", "gushi", "xinJing"]},
    {"text": "不入虎穴，焉得虎子。", "author": "古训", "cats": ["yongqi", "chenggong", "gushi"]},
    {"text": "勇者无畏，智者不惑。", "author": "古训", "cats": ["yongqi", "zhihui", "gushi"]},
    {"text": "你若失去了财产，你只失去了一点；你若失去了荣誉，你就失去了很多。", "author": "歌德", "cats": ["yongqi", "rongYu", "rensheng"]},
    {"text": "你若失去了勇气，你就把一切都失去了。", "author": "歌德", "cats": ["yongqi", "rensheng"]},
    {"text": "路漫漫其修远兮，吾将上下而求索。", "author": "屈原", "cats": ["yongqi", "jianchi", "gushi"]},
    {"text": "亦余心之所善兮，虽九死其犹未悔。", "author": "屈原", "cats": ["yongqi", "jianchi", "gushi"]},
    {"text": "风萧萧兮易水寒，壮士一去兮不复还。", "author": "荆轲", "cats": ["yongqi", "beiZhuang", "gushi"]},
    {"text": "人生自古谁无死，留取丹心照汗青。", "author": "文天祥", "cats": ["yongqi", "aiGuo", "gushi"]},
    {"text": "我自横刀向天笑，去留肝胆两昆仑。", "author": "谭嗣同", "cats": ["yongqi", "haoQing", "gushi"]},
    {"text": "粉骨碎身浑不怕，要留清白在人间。", "author": "于谦", "cats": ["yongqi", "qingBai", "gushi"]},
    {"text": "苟利国家生死以，岂因祸福避趋之。", "author": "林则徐", "cats": ["yongqi", "aiGuo", "gushi"]},
    {"text": "真的猛士，敢于直面惨淡的人生，敢于正视淋漓的鲜血。", "author": "鲁迅", "cats": ["yongqi", "jianQiang", "mingren"]},

    # ===== 健康 =====
    {"text": "健康是人生第一财富。", "author": "爱默生", "cats": ["jiankang", "caiFu", "mingren"]},
    {"text": "身体是革命的本钱。", "author": "毛泽东", "cats": ["jiankang", "zhongYao", "mingren"]},
    {"text": "健康不是一切，但没有健康就没有一切。", "author": "佚名", "cats": ["jiankang", "zhongYao"]},
    {"text": "健康的人未察觉自己的健康，只有病人才懂得健康。", "author": "卡莱尔", "cats": ["jiankang", "zhenXi"]},
    {"text": "早睡早起，使人健康、富有、明智。", "author": "富兰克林", "cats": ["jiankang", "xiGuan"]},
    {"text": "运动是一切生命的源泉。", "author": "达·芬奇", "cats": ["jiankang", "yunDong"]},
    {"text": "健康的心理寓于健康的身体。", "author": "洛克", "cats": ["jiankang", "xinLi"]},
    {"text": "愉快的笑声是精神健康的可靠标记。", "author": "契诃夫", "cats": ["jiankang", "kuaile"]},
    {"text": "只有身体好才能学习好、工作好，才能均衡地发展。", "author": "宋庆龄", "cats": ["jiankang", "faZhan", "mingren"]},
    {"text": "一个人的身体，决不是个人的，要把它看作是社会的宝贵财富。", "author": "高士其", "cats": ["jiankang", "jiazhi"]},
    {"text": "笑一笑，十年少；愁一愁，白了头。", "author": "古训", "cats": ["jiankang", "kuaile", "gushi"]},
    {"text": "病从口入，祸从口出。", "author": "古训", "cats": ["jiankang", "jingYan", "gushi"]},
    {"text": "饭后百步走，活到九十九。", "author": "古训", "cats": ["jiankang", "yunDong", "gushi"]},
    {"text": "药补不如食补，食补不如神补。", "author": "古训", "cats": ["jiankang", "xinLing", "gushi"]},
    {"text": "三分治，七分养。", "author": "古训", "cats": ["jiankang", "yangSheng", "gushi"]},
    {"text": "上医治未病，中医治欲病，下医治已病。", "author": "黄帝内经", "cats": ["jiankang", "yuFang", "gushi"]},
    {"text": "静以修身，俭以养德。", "author": "诸葛亮", "cats": ["jiankang", "daode", "gushi"]},
    {"text": "非淡泊无以明志，非宁静无以致远。", "author": "诸葛亮", "cats": ["jiankang", "mengXiang", "gushi"]},
    {"text": "采菊东篱下，悠然见南山。", "author": "陶渊明", "cats": ["jiankang", "xianYi", "gushi"]},
    {"text": "饮食有节，起居有常。", "author": "黄帝内经", "cats": ["jiankang", "yangSheng", "gushi"]},

    # ===== 工作/事业 =====
    {"text": "天才就是长期劳动的结果。", "author": "牛顿", "cats": ["gongzuo", "lizhi", "mingren"]},
    {"text": "成功等于百分之九十九的汗水加百分之一的灵感。", "author": "爱迪生", "cats": ["gongzuo", "chenggong", "lizhi"]},
    {"text": "工作就是人生的价值，人生的欢乐，也是幸福之所在。", "author": "罗丹", "cats": ["gongzuo", "jiazhi", "kuaile"]},
    {"text": "人生在勤，不索何获。", "author": "张衡", "cats": ["gongzuo", "lizhi", "gushi"]},
    {"text": "业精于勤荒于嬉，行成于思毁于随。", "author": "韩愈", "cats": ["gongzuo", "xuexi", "gushi"]},
    {"text": "一勤天下无难事。", "author": "古训", "cats": ["gongzuo", "lizhi"]},
    {"text": "今天所做之事勿候明天，自己所做之事勿候他人。", "author": "歌德", "cats": ["gongzuo", "shijian"]},
    {"text": "把每一件简单的事做好就是不简单。", "author": "张瑞敏", "cats": ["gongzuo", "chenggong"]},
    {"text": "世上没有绝望的处境，只有对处境绝望的人。", "author": "佚名", "cats": ["gongzuo", "yongqi"]},
    {"text": "行动是治愈恐惧的良药，而犹豫拖延将不断滋养恐惧。", "author": "卡耐基", "cats": ["gongzuo", "yongqi"]},
    {"text": "不要等待机会，而要创造机会。", "author": "萧伯纳", "cats": ["gongzuo", "mingYun"]},
    {"text": "一个有信念者所开发出的力量，大于个只有兴趣者。", "author": "梭罗", "cats": ["gongzuo", "zixin"]},
    {"text": "每一发奋努力的背后，必有加倍的赏赐。", "author": "佚名", "cats": ["gongzuo", "chenggong"]},
    {"text": "人生伟业的建立，不在能知，乃在能行。", "author": "赫胥黎", "cats": ["gongzuo", "chenggong", "rensheng"]},
    {"text": "任何的限制，都是从自己的内心开始的。", "author": "佚名", "cats": ["gongzuo", "zixin"]},
    {"text": "不想当将军的士兵不是好士兵。", "author": "拿破仑", "cats": ["gongzuo", "mengXiang", "mingren"]},
    {"text": "千里之行，始于足下。", "author": "老子", "cats": ["gongzuo", "jianchi", "gushi"]},
    {"text": "不积跬步，无以至千里。", "author": "荀子", "cats": ["gongzuo", "jianchi", "gushi"]},
    {"text": "书山有路勤为径，学海无涯苦作舟。", "author": "韩愈", "cats": ["gongzuo", "xuexi", "gushi"]},
    {"text": "天才在于积累，聪明在于勤奋。", "author": "华罗庚", "cats": ["gongzuo", "xuexi", "mingren"]},

    # ===== 习惯/自律 =====
    {"text": "优秀是一种习惯。", "author": "亚里士多德", "cats": ["xiguan", "youXiu", "mingren"]},
    {"text": "习惯形成性格，性格决定命运。", "author": "凯恩斯", "cats": ["xiguan", "xingGe", "mingYun"]},
    {"text": "静以修身，俭以养德。", "author": "诸葛亮", "cats": ["xiguan", "daode", "gushi"]},
    {"text": "美德大都包含在良好的习惯之内。", "author": "帕利克", "cats": ["xiguan", "daode"]},
    {"text": "习惯不加以抑制，不久它就会变成你生活上的必需品了。", "author": "奥古斯丁", "cats": ["xiguan", "yiZhi"]},
    {"text": "起先是我们造成习惯，后来是习惯造成我们。", "author": "王尔德", "cats": ["xiguan", "yingXiang"]},
    {"text": "孩子成功教育从好习惯培养开始。", "author": "巴金", "cats": ["xiguan", "jiaoYu", "mingren"]},
    {"text": "总以某种固定方式行事，人便能养成习惯。", "author": "亚里士多德", "cats": ["xiguan", "xingCheng"]},
    {"text": "习惯就是习惯，谁也不能将其扔出窗外，只能一步一步地引下楼。", "author": "马克·吐温", "cats": ["xiguan", "gaiBian"]},
    {"text": "习惯比天性更顽固。", "author": "昆图斯", "cats": ["xiguan", "wanGu"]},
    {"text": "自律给我自由。", "author": "佚名", "cats": ["xiguan", "ziYou", "ziLv"]},
    {"text": "你有多自律，就有多自由。", "author": "佚名", "cats": ["xiguan", "ziYou", "ziLv"]},
    {"text": "自律是最高级的自由。", "author": "佚名", "cats": ["xiguan", "ziYou", "ziLv"]},
    {"text": "越自律，越优秀。", "author": "佚名", "cats": ["xiguan", "youXiu", "ziLv"]},
    {"text": "一个人如果不能控制自己，就不能控制别人。", "author": "佚名", "cats": ["xiguan", "ziLv", "guanLi"]},
    {"text": "控制自己的欲望，才能控制自己的人生。", "author": "佚名", "cats": ["xiguan", "yuWang", "renSheng"]},
    {"text": "早睡早起是最好的化妆品。", "author": "佚名", "cats": ["xiguan", "meiLi", "jianKang"]},
    {"text": "读书是最好的修行。", "author": "佚名", "cats": ["xiguan", "dushu", "xiuXing"]},
    {"text": "每天进步一点点。", "author": "佚名", "cats": ["xiguan", "jinBu", "jianChi"]},
    {"text": "坚持21天，就能养成一个好习惯。", "author": "佚名", "cats": ["xiguan", "jianChi", "yangCheng"]},

    # ===== 思念/乡愁 =====
    {"text": "但愿人长久，千里共婵娟。", "author": "苏轼", "cats": ["siyuan", "gushi", "yueLiang"]},
    {"text": "举头望明月，低头思故乡。", "author": "李白", "cats": ["siyuan", "xiangChou", "gushi"]},
    {"text": "独在异乡为异客，每逢佳节倍思亲。", "author": "王维", "cats": ["siyuan", "xiangChou", "gushi"]},
    {"text": "两情若是久长时，又岂在朝朝暮暮。", "author": "秦观", "cats": ["siyuan", "aiqing", "gushi"]},
    {"text": "衣带渐宽终不悔，为伊消得人憔悴。", "author": "柳永", "cats": ["siyuan", "aiqing", "gushi"]},
    {"text": "一日不见，如三秋兮。", "author": "诗经", "cats": ["siyuan", "aiqing", "gushi"]},
    {"text": "红豆生南国，春来发几枝。", "author": "王维", "cats": ["siyuan", "aiqing", "gushi"]},
    {"text": "海上生明月，天涯共此时。", "author": "张九龄", "cats": ["siyuan", "gushi", "youqing"]},
    {"text": "露从今夜白，月是故乡明。", "author": "杜甫", "cats": ["siyuan", "xiangChou", "gushi"]},
    {"text": "此夜曲中闻折柳，何人不起故园情。", "author": "李白", "cats": ["siyuan", "xiangChou", "gushi"]},
    {"text": "春风又绿江南岸，明月何时照我还？", "author": "王安石", "cats": ["siyuan", "xiangChou", "gushi"]},
    {"text": "春风得意马蹄疾，一日看尽长安花。", "author": "孟郊", "cats": ["siyuan", "kuaile", "gushi"]},
    {"text": "烽火连三月，家书抵万金。", "author": "杜甫", "cats": ["siyuan", "jiaTing", "gushi"]},
    {"text": "感时花溅泪，恨别鸟惊心。", "author": "杜甫", "cats": ["siyuan", "youShang", "gushi"]},
    {"text": "月落乌啼霜满天，江枫渔火对愁眠。", "author": "张继", "cats": ["siyuan", "youShang", "gushi"]},
    {"text": "姑苏城外寒山寺，夜半钟声到客船。", "author": "张继", "cats": ["siyuan", "youShang", "gushi"]},
    {"text": "日暮乡关何处是？烟波江上使人愁。", "author": "崔颢", "cats": ["siyuan", "xiangChou", "gushi"]},
    {"text": "黄鹤一去不复返，白云千载空悠悠。", "author": "崔颢", "cats": ["siyuan", "shiJian", "gushi"]},
    {"text": "剪不断，理还乱，是离愁。", "author": "李煜", "cats": ["siyuan", "youShang", "gushi"]},
    {"text": "问君能有几多愁？恰似一江春水向东流。", "author": "李煜", "cats": ["siyuan", "youShang", "gushi"]},

    # ===== 离别 =====
    {"text": "莫愁前路无知己，天下谁人不识君。", "author": "高适", "cats": ["liuxue", "youqing", "gushi"]},
    {"text": "海内存知己，天涯若比邻。", "author": "王勃", "cats": ["liuxue", "youqing", "gushi"]},
    {"text": "劝君更尽一杯酒，西出阳关无故人。", "author": "王维", "cats": ["liuxue", "youqing", "gushi"]},
    {"text": "桃花潭水深千尺，不及汪伦送我情。", "author": "李白", "cats": ["liuxue", "youqing", "gushi"]},
    {"text": "相见时难别亦难，东风无力百花残。", "author": "李商隐", "cats": ["liuxue", "aiqing", "gushi"]},
    {"text": "多情自古伤离别，更那堪，冷落清秋节。", "author": "柳永", "cats": ["liuxue", "tongku", "gushi"]},
    {"text": "人有悲欢离合，月有阴晴圆缺。", "author": "苏轼", "cats": ["liuxue", "rensheng", "gushi"]},
    {"text": "天下没有不散的筵席。", "author": "古训", "cats": ["liuxue", "rensheng"]},
    {"text": "离别是为了更好的相聚。", "author": "佚名", "cats": ["liuxue", "meihao"]},
    {"text": "轻轻的我走了，正如我轻轻的来。", "author": "徐志摩", "cats": ["liuxue", "shiGe"]},
    {"text": "故人西辞黄鹤楼，烟花三月下扬州。", "author": "李白", "cats": ["liuxue", "youqing", "gushi"]},
    {"text": "孤帆远影碧空尽，唯见长江天际流。", "author": "李白", "cats": ["liuxue", "youqing", "gushi"]},
    {"text": "浮云游子意，落日故人情。", "author": "李白", "cats": ["liuxue", "youqing", "gushi"]},
    {"text": "挥手自兹去，萧萧班马鸣。", "author": "李白", "cats": ["liuxue", "youqing", "gushi"]},
    {"text": "洛阳亲友如相问，一片冰心在玉壶。", "author": "王昌龄", "cats": ["liuxue", "youqing", "gushi"]},
    {"text": "寒雨连江夜入吴，平明送客楚山孤。", "author": "王昌龄", "cats": ["liuxue", "songBie", "gushi"]},
    {"text": "山中相送罢，日暮掩柴扉。", "author": "王维", "cats": ["liuxue", "songBie", "gushi"]},
    {"text": "春草明年绿，王孙归不归？", "author": "王维", "cats": ["liuxue", "siNian", "gushi"]},
    {"text": "又送王孙去，萋萋满别情。", "author": "白居易", "cats": ["liuxue", "songBie", "gushi"]},
    {"text": "无为在歧路，儿女共沾巾。", "author": "王勃", "cats": ["liuxue", "yongQi", "gushi"]},

    # ===== 美丽 =====
    {"text": "生活中不是缺少美，而是缺少发现美的眼睛。", "author": "罗丹", "cats": ["meili", "kuaile", "mingren"]},
    {"text": "美是到处都有的。对于我们的眼睛，不是缺少美，而是缺少发现。", "author": "罗丹", "cats": ["meili", "faXian", "mingren"]},
    {"text": "美是道德上的善的象征。", "author": "康德", "cats": ["meili", "daode"]},
    {"text": "人并不是因为美丽才可爱，而是因为可爱才美丽。", "author": "托尔斯泰", "cats": ["meili", "keAi"]},
    {"text": "美丽的心灵是永恒的春天。", "author": "威·布莱克", "cats": ["meili", "xinLing"]},
    {"text": "朴素是美的必要条件。", "author": "托尔斯泰", "cats": ["meili", "puSu"]},
    {"text": "美是上帝赐予的礼物。", "author": "亚里士多德", "cats": ["meili", "tianFu"]},
    {"text": "外貌美只能取悦一时，内心美方能经久不衰。", "author": "歌德", "cats": ["meili", "neiXin"]},
    {"text": "我们周围有光也有颜色，但是我们自己的眼里如果没有光和颜色，也就看不到外面的光和颜色了。", "author": "歌德", "cats": ["meili", "xinLing"]},
    {"text": "落霞与孤鹜齐飞，秋水共长天一色。", "author": "王勃", "cats": ["meili", "zhuangGuan", "gushi"]},
    {"text": "大漠孤烟直，长河落日圆。", "author": "王维", "cats": ["meili", "zhuangGuan", "gushi"]},
    {"text": "明月松间照，清泉石上流。", "author": "王维", "cats": ["meili", "jingSe", "gushi"]},
    {"text": "空山新雨后，天气晚来秋。", "author": "王维", "cats": ["meili", "qiuTian", "gushi"]},
    {"text": "接天莲叶无穷碧，映日荷花别样红。", "author": "杨万里", "cats": ["meili", "xiaTian", "gushi"]},
    {"text": "停车坐爱枫林晚，霜叶红于二月花。", "author": "杜牧", "cats": ["meili", "qiuTian", "gushi"]},
    {"text": "忽如一夜春风来，千树万树梨花开。", "author": "岑参", "cats": ["meili", "dongTian", "gushi"]},
    {"text": "天街小雨润如酥，草色遥看近却无。", "author": "韩愈", "cats": ["meili", "chunTian", "gushi"]},
    {"text": "日出江花红胜火，春来江水绿如蓝。", "author": "白居易", "cats": ["meili", "chunTian", "gushi"]},
    {"text": "一道残阳铺水中，半江瑟瑟半江红。", "author": "白居易", "cats": ["meili", "jingSe", "gushi"]},
    {"text": "星垂平野阔，月涌大江流。", "author": "杜甫", "cats": ["meili", "zhuangGuan", "gushi"]},

    # ===== 幽默 =====
    {"text": "人生苦短，必须性感。", "author": "佚名", "cats": ["youmo", "rensheng"]},
    {"text": "我不是胖，我只是瘦的不明显。", "author": "佚名", "cats": ["youmo", "zixin"]},
    {"text": "世上无难事，只要肯放弃。", "author": "佚名", "cats": ["youmo", "daoLi"]},
    {"text": "当你觉得自己又丑又穷的时候，不要绝望，因为至少你的判断是对的。", "author": "佚名", "cats": ["youmo", "rensheng"]},
    {"text": "生活不止眼前的苟且，还有读不懂的诗和到不了的远方。", "author": "佚名", "cats": ["youmo", "xianShi"]},
    {"text": "没有伞的孩子必须努力奔跑，不然会被雨淋。", "author": "佚名", "cats": ["youmo", "lizhi"]},
    {"text": "钱不是万能的，但没有钱是万万不能的。", "author": "佚名", "cats": ["youmo", "xianShi"]},
    {"text": "我的优点是：我很帅；但是我的缺点是：我帅的不明显。", "author": "周立波", "cats": ["youmo", "zixin"]},
    {"text": "人生就像愤怒的小鸟，失败时总有几只猪在笑。", "author": "佚名", "cats": ["youmo", "shibai"]},
    {"text": "如果你觉得自己很牛，那你一定没见过真正的牛人。", "author": "佚名", "cats": ["youmo", "qianxu"]},
    {"text": "别人笑我太疯癫，我笑他人看不穿。", "author": "唐伯虎", "cats": ["youmo", "ziXin", "gushi"]},
    {"text": "人生苦短，必须及时行乐。", "author": "佚名", "cats": ["youmo", "kuaile"]},
    {"text": "我不是懒，我只是开启了省电模式。", "author": "佚名", "cats": ["youmo", "gaoXiao"]},
    {"text": "世上无难事，只怕有钱人。", "author": "佚名", "cats": ["youmo", "xianShi"]},
    {"text": "人生就像心电图，一帆风顺你就挂了。", "author": "佚名", "cats": ["youmo", "rensheng"]},
    {"text": "你以为有钱人很快乐吗？他们的快乐你根本想象不到。", "author": "佚名", "cats": ["youmo", "qian"]},
    {"text": "不要把我的容忍，当成你不要脸的资本。", "author": "佚名", "cats": ["youmo", "qiShi"]},
    {"text": "我不是人民币，做不到人人都喜欢。", "author": "佚名", "cats": ["youmo", "ziXin"]},
    {"text": "时间就像一张网，你撒在哪里，收获就在哪里。", "author": "佚名", "cats": ["youmo", "nuLi"]},
    {"text": "梦想还是要有的，万一见鬼了呢。", "author": "佚名", "cats": ["youmo", "mengXiang"]},

    # ===== 命运/机遇 =====
    {"text": "命运掌握在自己手中。", "author": "佚名", "cats": ["mingyun", "zixin"]},
    {"text": "我命由我不由天。", "author": "佚名", "cats": ["mingyun", "yongqi"]},
    {"text": "所谓活着的人，就是不断挑战的人，不断攀登命运险峰的人。", "author": "雨果", "cats": ["mingyun", "lizhi", "chengzhang"]},
    {"text": "命运压不垮一个人，只会使人坚强起来。", "author": "伯尔", "cats": ["mingyun", "jianqiang"]},
    {"text": "对于凌驾命运之上的人来说，信心就是生命的主宰。", "author": "海伦·凯勒", "cats": ["mingyun", "zixin"]},
    {"text": "当命运递给我一个酸的柠檬时，让我们设法把它制造成甜的柠檬汁。", "author": "雨果", "cats": ["mingyun", "kuaile"]},
    {"text": "一个人的性格决定他的际遇。", "author": "罗曼·罗兰", "cats": ["mingyun", "xingGe"]},
    {"text": "机会不会上门来找；只有人去找机会。", "author": "狄更斯", "cats": ["mingyun", "nuLi"]},
    {"text": "不要等待机会，而要创造机会。", "author": "萧伯纳", "cats": ["mingyun", "chuangZao"]},
    {"text": "命运给予我们的不是失望之酒，而是机会之杯。", "author": "尼克松", "cats": ["mingyun", "jiHui"]},
    {"text": "机会只偏爱有准备的头脑。", "author": "巴斯德", "cats": ["mingyun", "jiHui", "zhunBei"]},
    {"text": "时势造英雄，英雄造时势。", "author": "古训", "cats": ["mingyun", "yingXiong", "gushi"]},
    {"text": "谋事在人，成事在天。", "author": "古训", "cats": ["mingyun", "nuLi", "gushi"]},
    {"text": "天时不如地利，地利不如人和。", "author": "孟子", "cats": ["mingyun", "tuanJie", "gushi"]},
    {"text": "塞翁失马，焉知非福。", "author": "淮南子", "cats": ["mingyun", "zhiHui", "gushi"]},
    {"text": "机不可失，时不再来。", "author": "古训", "cats": ["mingyun", "jiHui", "gushi"]},
    {"text": "近水楼台先得月，向阳花木易为春。", "author": "苏麟", "cats": ["mingyun", "jiHui", "gushi"]},
    {"text": "有心栽花花不开，无心插柳柳成荫。", "author": "古训", "cats": ["mingyun", "yiWai", "gushi"]},
    {"text": "踏破铁鞋无觅处，得来全不费工夫。", "author": "古训", "cats": ["mingyun", "jiHui", "gushi"]},
    {"text": "山重水复疑无路，柳暗花明又一村。", "author": "陆游", "cats": ["mingyun", "xiWang", "gushi"]},

    # ===== 感恩 =====
    {"text": "谁言寸草心，报得三春晖。", "author": "孟郊", "cats": ["ganen", "jiaoting", "gushi"]},
    {"text": "鸦有反哺之义，羊有跪乳之恩。", "author": "古训", "cats": ["ganen", "jiaoting", "gushi"]},
    {"text": "滴水之恩，当涌泉相报。", "author": "古训", "cats": ["ganen", "gushi"]},
    {"text": "感恩是精神上的一种宝藏。", "author": "洛克", "cats": ["ganen", "jingshen"]},
    {"text": "不管一个人取得多么值得骄傲的成绩，都应该饮水思源。", "author": "居里夫人", "cats": ["ganen", "chenggong"]},
    {"text": "生活需要一颗感恩的心来创造，一颗感恩的心需要生活来滋养。", "author": "王符", "cats": ["ganen", "shenghuo"]},
    {"text": "父母之恩，水不能溺，火不能灭。", "author": "俄国谚语", "cats": ["ganen", "jiaoting"]},
    {"text": "没有感恩就没有真正的美德。", "author": "卢梭", "cats": ["ganen", "daode"]},
    {"text": "人世间最美丽的情景是出现在当我们怀念到母亲的时候。", "author": "莫泊桑", "cats": ["ganen", "jiaoting", "meihao"]},
    {"text": "一粥一饭当思来处不易，半丝半缕恒念物力维艰。", "author": "朱柏庐", "cats": ["ganen", "jieYue", "gushi"]},
    {"text": "吃水不忘挖井人。", "author": "古训", "cats": ["ganen", "gushi"]},
    {"text": "受人滴水之恩，当以涌泉相报。", "author": "古训", "cats": ["ganen", "gushi"]},
    {"text": "知遇之恩，当涌泉相报。", "author": "古训", "cats": ["ganen", "gushi"]},
    {"text": "知恩图报，善莫大焉。", "author": "古训", "cats": ["ganen", "daode", "gushi"]},
    {"text": "投我以桃，报之以李。", "author": "诗经", "cats": ["ganen", "youqing", "gushi"]},
    {"text": "投我以木瓜，报之以琼琚。", "author": "诗经", "cats": ["ganen", "youqing", "gushi"]},
    {"text": "谁言寸草心，报得三春晖。", "author": "孟郊", "cats": ["ganen", "muQin", "gushi"]},
    {"text": "春蚕到死丝方尽，蜡炬成灰泪始干。", "author": "李商隐", "cats": ["ganen", "fengXian", "gushi"]},
    {"text": "落红不是无情物，化作春泥更护花。", "author": "龚自珍", "cats": ["ganen", "fengXian", "gushi"]},
    {"text": "横眉冷对千夫指，俯首甘为孺子牛。", "author": "鲁迅", "cats": ["ganen", "fengXian", "mingren"]},

    # ===== 孤独 =====
    {"text": "古来圣贤皆寂寞，惟有饮者留其名。", "author": "李白", "cats": ["jimo", "gushi", "mingren"]},
    {"text": "孤独是一个人的狂欢，狂欢是一群人的孤独。", "author": "泰戈尔", "cats": ["jimo", "kuaile"]},
    {"text": "孤独，是忧愁的伴侣，也是精神活动的密友。", "author": "纪伯伦", "cats": ["jimo", "jingshen"]},
    {"text": "越是伟大的人，越能耐得住孤独。", "author": "佚名", "cats": ["jimo", "chengzhang"]},
    {"text": "孤独不是一种脾性，而是一种无奈。", "author": "余秋雨", "cats": ["jimo", "rensheng"]},
    {"text": "只有当一个人独处的时候，他才可以完全成为自己。", "author": "叔本华", "cats": ["jimo", "ziji"]},
    {"text": "孤独和寂寞不一样，寂寞会发慌，孤独则是饱满的。", "author": "陈果", "cats": ["jimo", "chengShu"]},
    {"text": "人生，总有一些路要一个人走。", "author": "佚名", "cats": ["jimo", "rensheng"]},
    {"text": "孤独是美丽的，置身于孤单之中，你会把全身心放松。", "author": "佚名", "cats": ["jimo", "kuaile"]},
    {"text": "非淡泊无以明志，非宁静无以致远。", "author": "诸葛亮", "cats": ["jimo", "mengxiang", "gushi"]},
    {"text": "前不见古人，后不见来者。", "author": "陈子昂", "cats": ["jimo", "gushi", "beiZhuang"]},
    {"text": "念天地之悠悠，独怆然而涕下。", "author": "陈子昂", "cats": ["jimo", "gushi", "beiZhuang"]},
    {"text": "举杯邀明月，对影成三人。", "author": "李白", "cats": ["jimo", "gushi", "yueLiang"]},
    {"text": "千山鸟飞绝，万径人踪灭。", "author": "柳宗元", "cats": ["jimo", "gushi", "dongTian"]},
    {"text": "孤舟蓑笠翁，独钓寒江雪。", "author": "柳宗元", "cats": ["jimo", "gushi", "dongTian"]},
    {"text": "独在异乡为异客，每逢佳节倍思亲。", "author": "王维", "cats": ["jimo", "xiangChou", "gushi"]},
    {"text": "深林人不知，明月来相照。", "author": "王维", "cats": ["jimo", "gushi", "youJing"]},
    {"text": "空山不见人，但闻人语响。", "author": "王维", "cats": ["jimo", "gushi", "youJing"]},
    {"text": "人闲桂花落，夜静春山空。", "author": "王维", "cats": ["jimo", "gushi", "youJing"]},
    {"text": "众鸟高飞尽，孤云独去闲。", "author": "李白", "cats": ["jimo", "gushi", "youJing"]},

    # ===== 理想 =====
    {"text": "志当存高远。", "author": "诸葛亮", "cats": ["lxiang", "lizhi", "gushi"]},
    {"text": "非淡泊无以明志，非宁静无以致远。", "author": "诸葛亮", "cats": ["lxiang", "gushi", "xinjing"]},
    {"text": "燕雀安知鸿鹄之志哉！", "author": "陈涉", "cats": ["lxiang", "lizhi", "mingren"]},
    {"text": "老骥伏枥，志在千里；烈士暮年，壮心不已。", "author": "曹操", "cats": ["lxiang", "lizhi", "gushi"]},
    {"text": "穷且益坚，不坠青云之志。", "author": "王勃", "cats": ["lxiang", "jianchi", "gushi"]},
    {"text": "不想当将军的士兵不是好士兵。", "author": "拿破仑", "cats": ["lxiang", "lizhi", "mingren"]},
    {"text": "理想是指路明灯。没有理想，就没有坚定的方向。", "author": "托尔斯泰", "cats": ["lxiang", "lizhi"]},
    {"text": "一个人的理想越崇高，生活越纯洁。", "author": "伏尼契", "cats": ["lxiang", "rensheng"]},
    {"text": "生活中没有理想的人，是可怜的。", "author": "屠格涅夫", "cats": ["lxiang", "lianMin"]},
    {"text": "人生最高之理想，在求达于真理。", "author": "李大钊", "cats": ["lxiang", "zhenLi", "mingren"]},
    {"text": "为中华之崛起而读书。", "author": "周恩来", "cats": ["lxiang", "xuexi", "mingren"]},
    {"text": "梦想还是要有的，万一实现了呢？", "author": "马云", "cats": ["lxiang", "mengxiang", "mingren"]},
    {"text": "大鹏一日同风起，扶摇直上九万里。", "author": "李白", "cats": ["lxiang", "lizhi", "gushi"]},
    {"text": "俱怀逸兴壮思飞，欲上青天揽明月。", "author": "李白", "cats": ["lxiang", "lizhi", "gushi"]},
    {"text": "长风破浪会有时，直挂云帆济沧海。", "author": "李白", "cats": ["lxiang", "mengXiang", "gushi"]},
    {"text": "会当凌绝顶，一览众山小。", "author": "杜甫", "cats": ["lxiang", "lizhi", "gushi"]},
    {"text": "安得广厦千万间，大庇天下寒士俱欢颜。", "author": "杜甫", "cats": ["lxiang", "aiGuo", "gushi"]},
    {"text": "出师未捷身先死，长使英雄泪满襟。", "author": "杜甫", "cats": ["lxiang", "beiZhuang", "gushi"]},
    {"text": "人生自古谁无死，留取丹心照汗青。", "author": "文天祥", "cats": ["lxiang", "aiGuo", "gushi"]},
    {"text": "粉骨碎身浑不怕，要留清白在人间。", "author": "于谦", "cats": ["lxiang", "qingBai", "gushi"]},

    # ===== 语录/现代 =====
    {"text": "愿你出走半生，归来仍是少年。", "author": "佚名", "cats": ["yulu", "meihao", "benXin"]},
    {"text": "生活不止眼前的苟且，还有诗和远方的田野。", "author": "高晓松", "cats": ["yulu", "mengxiang", "meihao"]},
    {"text": "我不去想是否能够成功，既然选择了远方，便只顾风雨兼程。", "author": "汪国真", "cats": ["yulu", "jianchi", "mengxiang"]},
    {"text": "既然选择了地平线，留给世界的只能是背影。", "author": "汪国真", "cats": ["yulu", "yongQi", "mengxiang"]},
    {"text": "没有比脚更长的路，没有比人更高的山。", "author": "汪国真", "cats": ["yulu", "jianchi", "lizhi"]},
    {"text": "你若有一个不屈的灵魂，脚下就会有一片坚实的土地。", "author": "汪国真", "cats": ["yulu", "jianqiang", "lizhi"]},
    {"text": "黑夜给了我黑色的眼睛，我却用它寻找光明。", "author": "顾城", "cats": ["yulu", "guangMing", "xiWang"]},
    {"text": "卑鄙是卑鄙者的通行证，高尚是高尚者的墓志铭。", "author": "北岛", "cats": ["yulu", "sheHui", "siKao"]},
    {"text": "从明天起，做一个幸福的人，喂马、劈柴，周游世界。", "author": "海子", "cats": ["yulu", "xingfu", "meihao"]},
    {"text": "面朝大海，春暖花开。", "author": "海子", "cats": ["yulu", "meihao", "xingfu"]},
    {"text": "要有最朴素的生活，与最遥远的梦想。", "author": "七堇年", "cats": ["yulu", "mengxiang", "puSu"]},
    {"text": "生如夏花之绚烂，死如秋叶之静美。", "author": "泰戈尔", "cats": ["yulu", "shengMing", "meihao"]},
    {"text": "眼睛为她下着雨，心却为她打着伞，这就是爱情。", "author": "泰戈尔", "cats": ["yulu", "aiqing", "shiYi"]},
    {"text": "你今天受的苦，吃的亏，担的责，扛的罪，忍的痛，到最后都会变成光，照亮你的路。", "author": "泰戈尔", "cats": ["yulu", "tongKu", "chengZhang"]},
    {"text": "世界以痛吻我，要我报之以歌。", "author": "泰戈尔", "cats": ["yulu", "tongKu", "jianQiang"]},
    {"text": "我们把世界看错，反说它欺骗了我们。", "author": "泰戈尔", "cats": ["yulu", "zhiHui", "ziSheng"]},
    {"text": "你看不见你自己，你所看见的只是你的影子。", "author": "泰戈尔", "cats": ["yulu", "ziSheng", "zhiHui"]},
    {"text": "鸟儿愿为一朵云，云儿愿为一只鸟。", "author": "泰戈尔", "cats": ["yulu", "xiangWang", "meihao"]},
    {"text": "使卵石臻于完美的，并非锤的打击，而是水的且歌且舞。", "author": "泰戈尔", "cats": ["yulu", "chengZhang", "shiJian"]},
    {"text": "不是槌的打击，乃是水的载歌载舞，使鹅卵石臻于完美。", "author": "泰戈尔", "cats": ["yulu", "wenRou", "chengZhang"]},
]

def main():
    print(f"额外名言数量: {len(EXTRA_QUOTES)}")

if __name__ == "__main__":
    main()
